/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.pacnet.connect.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the AccessRequest service. Represents a row in the &quot;Access_Request&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.pacnet.connect.model.impl.AccessRequestModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.pacnet.connect.model.impl.AccessRequestImpl}.
 * </p>
 *
 * @author CloudSmartz
 * @see AccessRequest
 * @see com.pacnet.connect.model.impl.AccessRequestImpl
 * @see com.pacnet.connect.model.impl.AccessRequestModelImpl
 * @generated
 */
public interface AccessRequestModel extends BaseModel<AccessRequest> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a access request model instance should use the {@link AccessRequest} interface instead.
	 */

	/**
	 * Returns the primary key of this access request.
	 *
	 * @return the primary key of this access request
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this access request.
	 *
	 * @param primaryKey the primary key of this access request
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this access request.
	 *
	 * @return the ID of this access request
	 */
	public long getId();

	/**
	 * Sets the ID of this access request.
	 *
	 * @param id the ID of this access request
	 */
	public void setId(long id);

	/**
	 * Returns the facility ID of this access request.
	 *
	 * @return the facility ID of this access request
	 */
	public long getFacilityId();

	/**
	 * Sets the facility ID of this access request.
	 *
	 * @param facilityId the facility ID of this access request
	 */
	public void setFacilityId(long facilityId);

	/**
	 * Returns the customer ID of this access request.
	 *
	 * @return the customer ID of this access request
	 */
	public long getCustomerId();

	/**
	 * Sets the customer ID of this access request.
	 *
	 * @param customerId the customer ID of this access request
	 */
	public void setCustomerId(long customerId);

	/**
	 * Returns the visitor ID of this access request.
	 *
	 * @return the visitor ID of this access request
	 */
	public long getVisitorId();

	/**
	 * Sets the visitor ID of this access request.
	 *
	 * @param visitorId the visitor ID of this access request
	 */
	public void setVisitorId(long visitorId);

	/**
	 * Returns the access request status ID of this access request.
	 *
	 * @return the access request status ID of this access request
	 */
	public long getAccessRequestStatusId();

	/**
	 * Sets the access request status ID of this access request.
	 *
	 * @param accessRequestStatusId the access request status ID of this access request
	 */
	public void setAccessRequestStatusId(long accessRequestStatusId);

	/**
	 * Returns the date of visit of this access request.
	 *
	 * @return the date of visit of this access request
	 */
	public Date getDateOfVisit();

	/**
	 * Sets the date of visit of this access request.
	 *
	 * @param dateOfVisit the date of visit of this access request
	 */
	public void setDateOfVisit(Date dateOfVisit);

	/**
	 * Returns the tentative time in of this access request.
	 *
	 * @return the tentative time in of this access request
	 */
	public long getTentativeTimeIn();

	/**
	 * Sets the tentative time in of this access request.
	 *
	 * @param tentativeTimeIn the tentative time in of this access request
	 */
	public void setTentativeTimeIn(long tentativeTimeIn);

	/**
	 * Returns the tentative time out of this access request.
	 *
	 * @return the tentative time out of this access request
	 */
	public long getTentativeTimeOut();

	/**
	 * Sets the tentative time out of this access request.
	 *
	 * @param tentativeTimeOut the tentative time out of this access request
	 */
	public void setTentativeTimeOut(long tentativeTimeOut);

	/**
	 * Returns the note of this access request.
	 *
	 * @return the note of this access request
	 */
	@AutoEscape
	public String getNote();

	/**
	 * Sets the note of this access request.
	 *
	 * @param note the note of this access request
	 */
	public void setNote(String note);

	/**
	 * Returns the is external visitor of this access request.
	 *
	 * @return the is external visitor of this access request
	 */
	public boolean getIsExternalVisitor();

	/**
	 * Returns <code>true</code> if this access request is is external visitor.
	 *
	 * @return <code>true</code> if this access request is is external visitor; <code>false</code> otherwise
	 */
	public boolean isIsExternalVisitor();

	/**
	 * Sets whether this access request is is external visitor.
	 *
	 * @param isExternalVisitor the is external visitor of this access request
	 */
	public void setIsExternalVisitor(boolean isExternalVisitor);

	/**
	 * Returns the is active of this access request.
	 *
	 * @return the is active of this access request
	 */
	public boolean getIsActive();

	/**
	 * Returns <code>true</code> if this access request is is active.
	 *
	 * @return <code>true</code> if this access request is is active; <code>false</code> otherwise
	 */
	public boolean isIsActive();

	/**
	 * Sets whether this access request is is active.
	 *
	 * @param isActive the is active of this access request
	 */
	public void setIsActive(boolean isActive);

	/**
	 * Returns the one time access of this access request.
	 *
	 * @return the one time access of this access request
	 */
	public boolean getOneTimeAccess();

	/**
	 * Returns <code>true</code> if this access request is one time access.
	 *
	 * @return <code>true</code> if this access request is one time access; <code>false</code> otherwise
	 */
	public boolean isOneTimeAccess();

	/**
	 * Sets whether this access request is one time access.
	 *
	 * @param oneTimeAccess the one time access of this access request
	 */
	public void setOneTimeAccess(boolean oneTimeAccess);

	/**
	 * Returns the date of visit gmt of this access request.
	 *
	 * @return the date of visit gmt of this access request
	 */
	public Date getDateOfVisitGmt();

	/**
	 * Sets the date of visit gmt of this access request.
	 *
	 * @param dateOfVisitGmt the date of visit gmt of this access request
	 */
	public void setDateOfVisitGmt(Date dateOfVisitGmt);

	/**
	 * Returns the date of time out gmt of this access request.
	 *
	 * @return the date of time out gmt of this access request
	 */
	public Date getDateOfTimeOutGmt();

	/**
	 * Sets the date of time out gmt of this access request.
	 *
	 * @param dateOfTimeOutGmt the date of time out gmt of this access request
	 */
	public void setDateOfTimeOutGmt(Date dateOfTimeOutGmt);

	/**
	 * Returns the created on of this access request.
	 *
	 * @return the created on of this access request
	 */
	public Date getCreatedOn();

	/**
	 * Sets the created on of this access request.
	 *
	 * @param createdOn the created on of this access request
	 */
	public void setCreatedOn(Date createdOn);

	/**
	 * Returns the created by of this access request.
	 *
	 * @return the created by of this access request
	 */
	@AutoEscape
	public String getCreatedBy();

	/**
	 * Sets the created by of this access request.
	 *
	 * @param createdBy the created by of this access request
	 */
	public void setCreatedBy(String createdBy);

	/**
	 * Returns the updated on of this access request.
	 *
	 * @return the updated on of this access request
	 */
	public Date getUpdatedOn();

	/**
	 * Sets the updated on of this access request.
	 *
	 * @param updatedOn the updated on of this access request
	 */
	public void setUpdatedOn(Date updatedOn);

	/**
	 * Returns the updated by of this access request.
	 *
	 * @return the updated by of this access request
	 */
	@AutoEscape
	public String getUpdatedBy();

	/**
	 * Sets the updated by of this access request.
	 *
	 * @param updatedBy the updated by of this access request
	 */
	public void setUpdatedBy(String updatedBy);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(AccessRequest accessRequest);

	public int hashCode();

	public CacheModel<AccessRequest> toCacheModel();

	public AccessRequest toEscapedModel();

	public String toString();

	public String toXmlString();
}