/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.pacnet.connect.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the AccessRequestStatus service. Represents a row in the &quot;Access_Request_Status&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.pacnet.connect.model.impl.AccessRequestStatusModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.pacnet.connect.model.impl.AccessRequestStatusImpl}.
 * </p>
 *
 * @author CloudSmartz
 * @see AccessRequestStatus
 * @see com.pacnet.connect.model.impl.AccessRequestStatusImpl
 * @see com.pacnet.connect.model.impl.AccessRequestStatusModelImpl
 * @generated
 */
public interface AccessRequestStatusModel extends BaseModel<AccessRequestStatus> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a access request status model instance should use the {@link AccessRequestStatus} interface instead.
	 */

	/**
	 * Returns the primary key of this access request status.
	 *
	 * @return the primary key of this access request status
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this access request status.
	 *
	 * @param primaryKey the primary key of this access request status
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this access request status.
	 *
	 * @return the ID of this access request status
	 */
	public long getId();

	/**
	 * Sets the ID of this access request status.
	 *
	 * @param id the ID of this access request status
	 */
	public void setId(long id);

	/**
	 * Returns the name of this access request status.
	 *
	 * @return the name of this access request status
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this access request status.
	 *
	 * @param name the name of this access request status
	 */
	public void setName(String name);

	/**
	 * Returns the description of this access request status.
	 *
	 * @return the description of this access request status
	 */
	public long getDescription();

	/**
	 * Sets the description of this access request status.
	 *
	 * @param description the description of this access request status
	 */
	public void setDescription(long description);

	/**
	 * Returns the is active of this access request status.
	 *
	 * @return the is active of this access request status
	 */
	public boolean getIsActive();

	/**
	 * Returns <code>true</code> if this access request status is is active.
	 *
	 * @return <code>true</code> if this access request status is is active; <code>false</code> otherwise
	 */
	public boolean isIsActive();

	/**
	 * Sets whether this access request status is is active.
	 *
	 * @param isActive the is active of this access request status
	 */
	public void setIsActive(boolean isActive);

	/**
	 * Returns the created on of this access request status.
	 *
	 * @return the created on of this access request status
	 */
	public Date getCreatedOn();

	/**
	 * Sets the created on of this access request status.
	 *
	 * @param createdOn the created on of this access request status
	 */
	public void setCreatedOn(Date createdOn);

	/**
	 * Returns the created by of this access request status.
	 *
	 * @return the created by of this access request status
	 */
	@AutoEscape
	public String getCreatedBy();

	/**
	 * Sets the created by of this access request status.
	 *
	 * @param createdBy the created by of this access request status
	 */
	public void setCreatedBy(String createdBy);

	/**
	 * Returns the updated on of this access request status.
	 *
	 * @return the updated on of this access request status
	 */
	public Date getUpdatedOn();

	/**
	 * Sets the updated on of this access request status.
	 *
	 * @param updatedOn the updated on of this access request status
	 */
	public void setUpdatedOn(Date updatedOn);

	/**
	 * Returns the updated by of this access request status.
	 *
	 * @return the updated by of this access request status
	 */
	@AutoEscape
	public String getUpdatedBy();

	/**
	 * Sets the updated by of this access request status.
	 *
	 * @param updatedBy the updated by of this access request status
	 */
	public void setUpdatedBy(String updatedBy);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(AccessRequestStatus accessRequestStatus);

	public int hashCode();

	public CacheModel<AccessRequestStatus> toCacheModel();

	public AccessRequestStatus toEscapedModel();

	public String toString();

	public String toXmlString();
}