/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.pacnet.connect.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the AccessLog service. Represents a row in the &quot;Access_Log&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.pacnet.connect.model.impl.AccessLogModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.pacnet.connect.model.impl.AccessLogImpl}.
 * </p>
 *
 * @author CloudSmartz
 * @see AccessLog
 * @see com.pacnet.connect.model.impl.AccessLogImpl
 * @see com.pacnet.connect.model.impl.AccessLogModelImpl
 * @generated
 */
public interface AccessLogModel extends BaseModel<AccessLog> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a access log model instance should use the {@link AccessLog} interface instead.
	 */

	/**
	 * Returns the primary key of this access log.
	 *
	 * @return the primary key of this access log
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this access log.
	 *
	 * @param primaryKey the primary key of this access log
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this access log.
	 *
	 * @return the ID of this access log
	 */
	public long getId();

	/**
	 * Sets the ID of this access log.
	 *
	 * @param id the ID of this access log
	 */
	public void setId(long id);

	/**
	 * Returns the access request ID of this access log.
	 *
	 * @return the access request ID of this access log
	 */
	public long getAccessRequestId();

	/**
	 * Sets the access request ID of this access log.
	 *
	 * @param accessRequestId the access request ID of this access log
	 */
	public void setAccessRequestId(long accessRequestId);

	/**
	 * Returns the facility user mapping ID of this access log.
	 *
	 * @return the facility user mapping ID of this access log
	 */
	public long getFacilityUserMappingId();

	/**
	 * Sets the facility user mapping ID of this access log.
	 *
	 * @param facilityUserMappingId the facility user mapping ID of this access log
	 */
	public void setFacilityUserMappingId(long facilityUserMappingId);

	/**
	 * Returns the actual date of visit of this access log.
	 *
	 * @return the actual date of visit of this access log
	 */
	public Date getActualDateOfVisit();

	/**
	 * Sets the actual date of visit of this access log.
	 *
	 * @param actualDateOfVisit the actual date of visit of this access log
	 */
	public void setActualDateOfVisit(Date actualDateOfVisit);

	/**
	 * Returns the time in of this access log.
	 *
	 * @return the time in of this access log
	 */
	public long getTimeIn();

	/**
	 * Sets the time in of this access log.
	 *
	 * @param timeIn the time in of this access log
	 */
	public void setTimeIn(long timeIn);

	/**
	 * Returns the time out of this access log.
	 *
	 * @return the time out of this access log
	 */
	public long getTimeOut();

	/**
	 * Sets the time out of this access log.
	 *
	 * @param timeOut the time out of this access log
	 */
	public void setTimeOut(long timeOut);

	/**
	 * Returns the note of this access log.
	 *
	 * @return the note of this access log
	 */
	@AutoEscape
	public String getNote();

	/**
	 * Sets the note of this access log.
	 *
	 * @param note the note of this access log
	 */
	public void setNote(String note);

	/**
	 * Returns the is active of this access log.
	 *
	 * @return the is active of this access log
	 */
	public boolean getIsActive();

	/**
	 * Returns <code>true</code> if this access log is is active.
	 *
	 * @return <code>true</code> if this access log is is active; <code>false</code> otherwise
	 */
	public boolean isIsActive();

	/**
	 * Sets whether this access log is is active.
	 *
	 * @param isActive the is active of this access log
	 */
	public void setIsActive(boolean isActive);

	/**
	 * Returns the created on of this access log.
	 *
	 * @return the created on of this access log
	 */
	public Date getCreatedOn();

	/**
	 * Sets the created on of this access log.
	 *
	 * @param createdOn the created on of this access log
	 */
	public void setCreatedOn(Date createdOn);

	/**
	 * Returns the created by of this access log.
	 *
	 * @return the created by of this access log
	 */
	@AutoEscape
	public String getCreatedBy();

	/**
	 * Sets the created by of this access log.
	 *
	 * @param createdBy the created by of this access log
	 */
	public void setCreatedBy(String createdBy);

	/**
	 * Returns the updated on of this access log.
	 *
	 * @return the updated on of this access log
	 */
	public Date getUpdatedOn();

	/**
	 * Sets the updated on of this access log.
	 *
	 * @param updatedOn the updated on of this access log
	 */
	public void setUpdatedOn(Date updatedOn);

	/**
	 * Returns the updated by of this access log.
	 *
	 * @return the updated by of this access log
	 */
	@AutoEscape
	public String getUpdatedBy();

	/**
	 * Sets the updated by of this access log.
	 *
	 * @param updatedBy the updated by of this access log
	 */
	public void setUpdatedBy(String updatedBy);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(AccessLog accessLog);

	public int hashCode();

	public CacheModel<AccessLog> toCacheModel();

	public AccessLog toEscapedModel();

	public String toString();

	public String toXmlString();
}