/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.pacnet.connect.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the AccessRequestNoteHistory service. Represents a row in the &quot;Access_Request_Note_History&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.pacnet.connect.model.impl.AccessRequestNoteHistoryModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.pacnet.connect.model.impl.AccessRequestNoteHistoryImpl}.
 * </p>
 *
 * @author CloudSmartz
 * @see AccessRequestNoteHistory
 * @see com.pacnet.connect.model.impl.AccessRequestNoteHistoryImpl
 * @see com.pacnet.connect.model.impl.AccessRequestNoteHistoryModelImpl
 * @generated
 */
public interface AccessRequestNoteHistoryModel extends BaseModel<AccessRequestNoteHistory> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a access request note history model instance should use the {@link AccessRequestNoteHistory} interface instead.
	 */

	/**
	 * Returns the primary key of this access request note history.
	 *
	 * @return the primary key of this access request note history
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this access request note history.
	 *
	 * @param primaryKey the primary key of this access request note history
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this access request note history.
	 *
	 * @return the ID of this access request note history
	 */
	public long getId();

	/**
	 * Sets the ID of this access request note history.
	 *
	 * @param id the ID of this access request note history
	 */
	public void setId(long id);

	/**
	 * Returns the access request ID of this access request note history.
	 *
	 * @return the access request ID of this access request note history
	 */
	public long getAccessRequestId();

	/**
	 * Sets the access request ID of this access request note history.
	 *
	 * @param accessRequestId the access request ID of this access request note history
	 */
	public void setAccessRequestId(long accessRequestId);

	/**
	 * Returns the customer ID of this access request note history.
	 *
	 * @return the customer ID of this access request note history
	 */
	public long getCustomerId();

	/**
	 * Sets the customer ID of this access request note history.
	 *
	 * @param customerId the customer ID of this access request note history
	 */
	public void setCustomerId(long customerId);

	/**
	 * Returns the note of this access request note history.
	 *
	 * @return the note of this access request note history
	 */
	@AutoEscape
	public String getNote();

	/**
	 * Sets the note of this access request note history.
	 *
	 * @param note the note of this access request note history
	 */
	public void setNote(String note);

	/**
	 * Returns the table name of this access request note history.
	 *
	 * @return the table name of this access request note history
	 */
	@AutoEscape
	public String getTableName();

	/**
	 * Sets the table name of this access request note history.
	 *
	 * @param tableName the table name of this access request note history
	 */
	public void setTableName(String tableName);

	/**
	 * Returns the is active of this access request note history.
	 *
	 * @return the is active of this access request note history
	 */
	public boolean getIsActive();

	/**
	 * Returns <code>true</code> if this access request note history is is active.
	 *
	 * @return <code>true</code> if this access request note history is is active; <code>false</code> otherwise
	 */
	public boolean isIsActive();

	/**
	 * Sets whether this access request note history is is active.
	 *
	 * @param isActive the is active of this access request note history
	 */
	public void setIsActive(boolean isActive);

	/**
	 * Returns the created on of this access request note history.
	 *
	 * @return the created on of this access request note history
	 */
	public Date getCreatedOn();

	/**
	 * Sets the created on of this access request note history.
	 *
	 * @param createdOn the created on of this access request note history
	 */
	public void setCreatedOn(Date createdOn);

	/**
	 * Returns the created by of this access request note history.
	 *
	 * @return the created by of this access request note history
	 */
	@AutoEscape
	public String getCreatedBy();

	/**
	 * Sets the created by of this access request note history.
	 *
	 * @param createdBy the created by of this access request note history
	 */
	public void setCreatedBy(String createdBy);

	/**
	 * Returns the updated on of this access request note history.
	 *
	 * @return the updated on of this access request note history
	 */
	public Date getUpdatedOn();

	/**
	 * Sets the updated on of this access request note history.
	 *
	 * @param updatedOn the updated on of this access request note history
	 */
	public void setUpdatedOn(Date updatedOn);

	/**
	 * Returns the updated by of this access request note history.
	 *
	 * @return the updated by of this access request note history
	 */
	@AutoEscape
	public String getUpdatedBy();

	/**
	 * Sets the updated by of this access request note history.
	 *
	 * @param updatedBy the updated by of this access request note history
	 */
	public void setUpdatedBy(String updatedBy);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(AccessRequestNoteHistory accessRequestNoteHistory);

	public int hashCode();

	public CacheModel<AccessRequestNoteHistory> toCacheModel();

	public AccessRequestNoteHistory toEscapedModel();

	public String toString();

	public String toXmlString();
}