/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.pacnet.connect.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the FacilityUserService service. Represents a row in the &quot;Facility_User_Service_Mapping&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.pacnet.connect.model.impl.FacilityUserServiceModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.pacnet.connect.model.impl.FacilityUserServiceImpl}.
 * </p>
 *
 * @author CloudSmartz
 * @see FacilityUserService
 * @see com.pacnet.connect.model.impl.FacilityUserServiceImpl
 * @see com.pacnet.connect.model.impl.FacilityUserServiceModelImpl
 * @generated
 */
public interface FacilityUserServiceModel extends BaseModel<FacilityUserService> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a facility user service model instance should use the {@link FacilityUserService} interface instead.
	 */

	/**
	 * Returns the primary key of this facility user service.
	 *
	 * @return the primary key of this facility user service
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this facility user service.
	 *
	 * @param primaryKey the primary key of this facility user service
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this facility user service.
	 *
	 * @return the ID of this facility user service
	 */
	public long getId();

	/**
	 * Sets the ID of this facility user service.
	 *
	 * @param id the ID of this facility user service
	 */
	public void setId(long id);

	/**
	 * Returns the facility user mapping ID of this facility user service.
	 *
	 * @return the facility user mapping ID of this facility user service
	 */
	public long getFacilityUserMappingId();

	/**
	 * Sets the facility user mapping ID of this facility user service.
	 *
	 * @param facilityUserMappingId the facility user mapping ID of this facility user service
	 */
	public void setFacilityUserMappingId(long facilityUserMappingId);

	/**
	 * Returns the facility service ID of this facility user service.
	 *
	 * @return the facility service ID of this facility user service
	 */
	public long getFacilityServiceId();

	/**
	 * Sets the facility service ID of this facility user service.
	 *
	 * @param facilityServiceId the facility service ID of this facility user service
	 */
	public void setFacilityServiceId(long facilityServiceId);

	/**
	 * Returns the is active of this facility user service.
	 *
	 * @return the is active of this facility user service
	 */
	public boolean getIsActive();

	/**
	 * Returns <code>true</code> if this facility user service is is active.
	 *
	 * @return <code>true</code> if this facility user service is is active; <code>false</code> otherwise
	 */
	public boolean isIsActive();

	/**
	 * Sets whether this facility user service is is active.
	 *
	 * @param isActive the is active of this facility user service
	 */
	public void setIsActive(boolean isActive);

	/**
	 * Returns the created on of this facility user service.
	 *
	 * @return the created on of this facility user service
	 */
	public Date getCreatedOn();

	/**
	 * Sets the created on of this facility user service.
	 *
	 * @param createdOn the created on of this facility user service
	 */
	public void setCreatedOn(Date createdOn);

	/**
	 * Returns the created by of this facility user service.
	 *
	 * @return the created by of this facility user service
	 */
	@AutoEscape
	public String getCreatedBy();

	/**
	 * Sets the created by of this facility user service.
	 *
	 * @param createdBy the created by of this facility user service
	 */
	public void setCreatedBy(String createdBy);

	/**
	 * Returns the updated on of this facility user service.
	 *
	 * @return the updated on of this facility user service
	 */
	public Date getUpdatedOn();

	/**
	 * Sets the updated on of this facility user service.
	 *
	 * @param updatedOn the updated on of this facility user service
	 */
	public void setUpdatedOn(Date updatedOn);

	/**
	 * Returns the updated by of this facility user service.
	 *
	 * @return the updated by of this facility user service
	 */
	@AutoEscape
	public String getUpdatedBy();

	/**
	 * Sets the updated by of this facility user service.
	 *
	 * @param updatedBy the updated by of this facility user service
	 */
	public void setUpdatedBy(String updatedBy);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(FacilityUserService facilityUserService);

	public int hashCode();

	public CacheModel<FacilityUserService> toCacheModel();

	public FacilityUserService toEscapedModel();

	public String toString();

	public String toXmlString();
}