/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.pacnet.connect.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the FacilityUserMapping service. Represents a row in the &quot;Facility_User_Mapping&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.pacnet.connect.model.impl.FacilityUserMappingModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.pacnet.connect.model.impl.FacilityUserMappingImpl}.
 * </p>
 *
 * @author CloudSmartz
 * @see FacilityUserMapping
 * @see com.pacnet.connect.model.impl.FacilityUserMappingImpl
 * @see com.pacnet.connect.model.impl.FacilityUserMappingModelImpl
 * @generated
 */
public interface FacilityUserMappingModel extends BaseModel<FacilityUserMapping> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a facility user mapping model instance should use the {@link FacilityUserMapping} interface instead.
	 */

	/**
	 * Returns the primary key of this facility user mapping.
	 *
	 * @return the primary key of this facility user mapping
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this facility user mapping.
	 *
	 * @param primaryKey the primary key of this facility user mapping
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this facility user mapping.
	 *
	 * @return the ID of this facility user mapping
	 */
	public long getId();

	/**
	 * Sets the ID of this facility user mapping.
	 *
	 * @param id the ID of this facility user mapping
	 */
	public void setId(long id);

	/**
	 * Returns the customer ID of this facility user mapping.
	 *
	 * @return the customer ID of this facility user mapping
	 */
	public long getCustomerId();

	/**
	 * Sets the customer ID of this facility user mapping.
	 *
	 * @param customerId the customer ID of this facility user mapping
	 */
	public void setCustomerId(long customerId);

	/**
	 * Returns the facilty ID of this facility user mapping.
	 *
	 * @return the facilty ID of this facility user mapping
	 */
	public long getFaciltyId();

	/**
	 * Sets the facilty ID of this facility user mapping.
	 *
	 * @param faciltyId the facilty ID of this facility user mapping
	 */
	public void setFaciltyId(long faciltyId);

	/**
	 * Returns the customer contact ID of this facility user mapping.
	 *
	 * @return the customer contact ID of this facility user mapping
	 */
	public long getCustomerContactId();

	/**
	 * Sets the customer contact ID of this facility user mapping.
	 *
	 * @param customerContactId the customer contact ID of this facility user mapping
	 */
	public void setCustomerContactId(long customerContactId);

	/**
	 * Returns the is active of this facility user mapping.
	 *
	 * @return the is active of this facility user mapping
	 */
	public boolean getIsActive();

	/**
	 * Returns <code>true</code> if this facility user mapping is is active.
	 *
	 * @return <code>true</code> if this facility user mapping is is active; <code>false</code> otherwise
	 */
	public boolean isIsActive();

	/**
	 * Sets whether this facility user mapping is is active.
	 *
	 * @param isActive the is active of this facility user mapping
	 */
	public void setIsActive(boolean isActive);

	/**
	 * Returns the non pacnet user ID of this facility user mapping.
	 *
	 * @return the non pacnet user ID of this facility user mapping
	 */
	public long getNonPacnetUserId();

	/**
	 * Sets the non pacnet user ID of this facility user mapping.
	 *
	 * @param nonPacnetUserId the non pacnet user ID of this facility user mapping
	 */
	public void setNonPacnetUserId(long nonPacnetUserId);

	/**
	 * Returns the non pacnet user uuid of this facility user mapping.
	 *
	 * @return the non pacnet user uuid of this facility user mapping
	 * @throws SystemException if a system exception occurred
	 */
	public String getNonPacnetUserUuid() throws SystemException;

	/**
	 * Sets the non pacnet user uuid of this facility user mapping.
	 *
	 * @param nonPacnetUserUuid the non pacnet user uuid of this facility user mapping
	 */
	public void setNonPacnetUserUuid(String nonPacnetUserUuid);

	/**
	 * Returns the created on of this facility user mapping.
	 *
	 * @return the created on of this facility user mapping
	 */
	public Date getCreatedOn();

	/**
	 * Sets the created on of this facility user mapping.
	 *
	 * @param createdOn the created on of this facility user mapping
	 */
	public void setCreatedOn(Date createdOn);

	/**
	 * Returns the created by of this facility user mapping.
	 *
	 * @return the created by of this facility user mapping
	 */
	@AutoEscape
	public String getCreatedBy();

	/**
	 * Sets the created by of this facility user mapping.
	 *
	 * @param createdBy the created by of this facility user mapping
	 */
	public void setCreatedBy(String createdBy);

	/**
	 * Returns the updated on of this facility user mapping.
	 *
	 * @return the updated on of this facility user mapping
	 */
	public Date getUpdatedOn();

	/**
	 * Sets the updated on of this facility user mapping.
	 *
	 * @param updatedOn the updated on of this facility user mapping
	 */
	public void setUpdatedOn(Date updatedOn);

	/**
	 * Returns the updated by of this facility user mapping.
	 *
	 * @return the updated by of this facility user mapping
	 */
	@AutoEscape
	public String getUpdatedBy();

	/**
	 * Sets the updated by of this facility user mapping.
	 *
	 * @param updatedBy the updated by of this facility user mapping
	 */
	public void setUpdatedBy(String updatedBy);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(FacilityUserMapping facilityUserMapping);

	public int hashCode();

	public CacheModel<FacilityUserMapping> toCacheModel();

	public FacilityUserMapping toEscapedModel();

	public String toString();

	public String toXmlString();
}