/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.pacnet.connect.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Facility service. Represents a row in the &quot;Facility&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.pacnet.connect.model.impl.FacilityModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.pacnet.connect.model.impl.FacilityImpl}.
 * </p>
 *
 * @author CloudSmartz
 * @see Facility
 * @see com.pacnet.connect.model.impl.FacilityImpl
 * @see com.pacnet.connect.model.impl.FacilityModelImpl
 * @generated
 */
public interface FacilityModel extends BaseModel<Facility> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a facility model instance should use the {@link Facility} interface instead.
	 */

	/**
	 * Returns the primary key of this facility.
	 *
	 * @return the primary key of this facility
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this facility.
	 *
	 * @param primaryKey the primary key of this facility
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this facility.
	 *
	 * @return the ID of this facility
	 */
	public long getId();

	/**
	 * Sets the ID of this facility.
	 *
	 * @param id the ID of this facility
	 */
	public void setId(long id);

	/**
	 * Returns the name of this facility.
	 *
	 * @return the name of this facility
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this facility.
	 *
	 * @param name the name of this facility
	 */
	public void setName(String name);

	/**
	 * Returns the address of this facility.
	 *
	 * @return the address of this facility
	 */
	@AutoEscape
	public String getAddress();

	/**
	 * Sets the address of this facility.
	 *
	 * @param address the address of this facility
	 */
	public void setAddress(String address);

	/**
	 * Returns the phone number of this facility.
	 *
	 * @return the phone number of this facility
	 */
	@AutoEscape
	public String getPhoneNumber();

	/**
	 * Sets the phone number of this facility.
	 *
	 * @param phoneNumber the phone number of this facility
	 */
	public void setPhoneNumber(String phoneNumber);

	/**
	 * Returns the city of this facility.
	 *
	 * @return the city of this facility
	 */
	@AutoEscape
	public String getCity();

	/**
	 * Sets the city of this facility.
	 *
	 * @param city the city of this facility
	 */
	public void setCity(String city);

	/**
	 * Returns the state ID of this facility.
	 *
	 * @return the state ID of this facility
	 */
	public long getStateId();

	/**
	 * Sets the state ID of this facility.
	 *
	 * @param stateId the state ID of this facility
	 */
	public void setStateId(long stateId);

	/**
	 * Returns the country ID of this facility.
	 *
	 * @return the country ID of this facility
	 */
	public long getCountryId();

	/**
	 * Sets the country ID of this facility.
	 *
	 * @param countryId the country ID of this facility
	 */
	public void setCountryId(long countryId);

	/**
	 * Returns the is third party of this facility.
	 *
	 * @return the is third party of this facility
	 */
	public int getIsThirdParty();

	/**
	 * Sets the is third party of this facility.
	 *
	 * @param isThirdParty the is third party of this facility
	 */
	public void setIsThirdParty(int isThirdParty);

	/**
	 * Returns the manager ID of this facility.
	 *
	 * @return the manager ID of this facility
	 */
	public long getManagerId();

	/**
	 * Sets the manager ID of this facility.
	 *
	 * @param managerId the manager ID of this facility
	 */
	public void setManagerId(long managerId);

	/**
	 * Returns the escalation email of this facility.
	 *
	 * @return the escalation email of this facility
	 */
	@AutoEscape
	public String getEscalationEmail();

	/**
	 * Sets the escalation email of this facility.
	 *
	 * @param escalationEmail the escalation email of this facility
	 */
	public void setEscalationEmail(String escalationEmail);

	/**
	 * Returns the is active of this facility.
	 *
	 * @return the is active of this facility
	 */
	public boolean getIsActive();

	/**
	 * Returns <code>true</code> if this facility is is active.
	 *
	 * @return <code>true</code> if this facility is is active; <code>false</code> otherwise
	 */
	public boolean isIsActive();

	/**
	 * Sets whether this facility is is active.
	 *
	 * @param isActive the is active of this facility
	 */
	public void setIsActive(boolean isActive);

	/**
	 * Returns the created on of this facility.
	 *
	 * @return the created on of this facility
	 */
	public Date getCreatedOn();

	/**
	 * Sets the created on of this facility.
	 *
	 * @param createdOn the created on of this facility
	 */
	public void setCreatedOn(Date createdOn);

	/**
	 * Returns the created by of this facility.
	 *
	 * @return the created by of this facility
	 */
	@AutoEscape
	public String getCreatedBy();

	/**
	 * Sets the created by of this facility.
	 *
	 * @param createdBy the created by of this facility
	 */
	public void setCreatedBy(String createdBy);

	/**
	 * Returns the updated on of this facility.
	 *
	 * @return the updated on of this facility
	 */
	public Date getUpdatedOn();

	/**
	 * Sets the updated on of this facility.
	 *
	 * @param updatedOn the updated on of this facility
	 */
	public void setUpdatedOn(Date updatedOn);

	/**
	 * Returns the updated by of this facility.
	 *
	 * @return the updated by of this facility
	 */
	@AutoEscape
	public String getUpdatedBy();

	/**
	 * Sets the updated by of this facility.
	 *
	 * @param updatedBy the updated by of this facility
	 */
	public void setUpdatedBy(String updatedBy);

	/**
	 * Returns the timezone of this facility.
	 *
	 * @return the timezone of this facility
	 */
	@AutoEscape
	public String getTimezone();

	/**
	 * Sets the timezone of this facility.
	 *
	 * @param timezone the timezone of this facility
	 */
	public void setTimezone(String timezone);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(Facility facility);

	public int hashCode();

	public CacheModel<Facility> toCacheModel();

	public Facility toEscapedModel();

	public String toString();

	public String toXmlString();
}