/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.pacnet.connect.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the FacilityExternalVisitor service. Represents a row in the &quot;Facility_External_Visitor&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.pacnet.connect.model.impl.FacilityExternalVisitorModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.pacnet.connect.model.impl.FacilityExternalVisitorImpl}.
 * </p>
 *
 * @author CloudSmartz
 * @see FacilityExternalVisitor
 * @see com.pacnet.connect.model.impl.FacilityExternalVisitorImpl
 * @see com.pacnet.connect.model.impl.FacilityExternalVisitorModelImpl
 * @generated
 */
public interface FacilityExternalVisitorModel extends BaseModel<FacilityExternalVisitor> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a facility external visitor model instance should use the {@link FacilityExternalVisitor} interface instead.
	 */

	/**
	 * Returns the primary key of this facility external visitor.
	 *
	 * @return the primary key of this facility external visitor
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this facility external visitor.
	 *
	 * @param primaryKey the primary key of this facility external visitor
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this facility external visitor.
	 *
	 * @return the ID of this facility external visitor
	 */
	public long getId();

	/**
	 * Sets the ID of this facility external visitor.
	 *
	 * @param id the ID of this facility external visitor
	 */
	public void setId(long id);

	/**
	 * Returns the facility ID of this facility external visitor.
	 *
	 * @return the facility ID of this facility external visitor
	 */
	public long getFacilityId();

	/**
	 * Sets the facility ID of this facility external visitor.
	 *
	 * @param facilityId the facility ID of this facility external visitor
	 */
	public void setFacilityId(long facilityId);

	/**
	 * Returns the access request ID of this facility external visitor.
	 *
	 * @return the access request ID of this facility external visitor
	 */
	public long getAccessRequestId();

	/**
	 * Sets the access request ID of this facility external visitor.
	 *
	 * @param accessRequestId the access request ID of this facility external visitor
	 */
	public void setAccessRequestId(long accessRequestId);

	/**
	 * Returns the name of this facility external visitor.
	 *
	 * @return the name of this facility external visitor
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this facility external visitor.
	 *
	 * @param name the name of this facility external visitor
	 */
	public void setName(String name);

	/**
	 * Returns the mobile number of this facility external visitor.
	 *
	 * @return the mobile number of this facility external visitor
	 */
	@AutoEscape
	public String getMobileNumber();

	/**
	 * Sets the mobile number of this facility external visitor.
	 *
	 * @param mobileNumber the mobile number of this facility external visitor
	 */
	public void setMobileNumber(String mobileNumber);

	/**
	 * Returns the email of this facility external visitor.
	 *
	 * @return the email of this facility external visitor
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this facility external visitor.
	 *
	 * @param email the email of this facility external visitor
	 */
	public void setEmail(String email);

	/**
	 * Returns the address of this facility external visitor.
	 *
	 * @return the address of this facility external visitor
	 */
	@AutoEscape
	public String getAddress();

	/**
	 * Sets the address of this facility external visitor.
	 *
	 * @param address the address of this facility external visitor
	 */
	public void setAddress(String address);

	/**
	 * Returns the company name of this facility external visitor.
	 *
	 * @return the company name of this facility external visitor
	 */
	@AutoEscape
	public String getCompanyName();

	/**
	 * Sets the company name of this facility external visitor.
	 *
	 * @param companyName the company name of this facility external visitor
	 */
	public void setCompanyName(String companyName);

	/**
	 * Returns the document type of this facility external visitor.
	 *
	 * @return the document type of this facility external visitor
	 */
	@AutoEscape
	public String getDocumentType();

	/**
	 * Sets the document type of this facility external visitor.
	 *
	 * @param documentType the document type of this facility external visitor
	 */
	public void setDocumentType(String documentType);

	/**
	 * Returns the document ID of this facility external visitor.
	 *
	 * @return the document ID of this facility external visitor
	 */
	@AutoEscape
	public String getDocumentId();

	/**
	 * Sets the document ID of this facility external visitor.
	 *
	 * @param documentId the document ID of this facility external visitor
	 */
	public void setDocumentId(String documentId);

	/**
	 * Returns the remarks of this facility external visitor.
	 *
	 * @return the remarks of this facility external visitor
	 */
	@AutoEscape
	public String getRemarks();

	/**
	 * Sets the remarks of this facility external visitor.
	 *
	 * @param remarks the remarks of this facility external visitor
	 */
	public void setRemarks(String remarks);

	/**
	 * Returns the is active of this facility external visitor.
	 *
	 * @return the is active of this facility external visitor
	 */
	public boolean getIsActive();

	/**
	 * Returns <code>true</code> if this facility external visitor is is active.
	 *
	 * @return <code>true</code> if this facility external visitor is is active; <code>false</code> otherwise
	 */
	public boolean isIsActive();

	/**
	 * Sets whether this facility external visitor is is active.
	 *
	 * @param isActive the is active of this facility external visitor
	 */
	public void setIsActive(boolean isActive);

	/**
	 * Returns the created on of this facility external visitor.
	 *
	 * @return the created on of this facility external visitor
	 */
	public Date getCreatedOn();

	/**
	 * Sets the created on of this facility external visitor.
	 *
	 * @param createdOn the created on of this facility external visitor
	 */
	public void setCreatedOn(Date createdOn);

	/**
	 * Returns the created by of this facility external visitor.
	 *
	 * @return the created by of this facility external visitor
	 */
	@AutoEscape
	public String getCreatedBy();

	/**
	 * Sets the created by of this facility external visitor.
	 *
	 * @param createdBy the created by of this facility external visitor
	 */
	public void setCreatedBy(String createdBy);

	/**
	 * Returns the updated on of this facility external visitor.
	 *
	 * @return the updated on of this facility external visitor
	 */
	public Date getUpdatedOn();

	/**
	 * Sets the updated on of this facility external visitor.
	 *
	 * @param updatedOn the updated on of this facility external visitor
	 */
	public void setUpdatedOn(Date updatedOn);

	/**
	 * Returns the updated by of this facility external visitor.
	 *
	 * @return the updated by of this facility external visitor
	 */
	@AutoEscape
	public String getUpdatedBy();

	/**
	 * Sets the updated by of this facility external visitor.
	 *
	 * @param updatedBy the updated by of this facility external visitor
	 */
	public void setUpdatedBy(String updatedBy);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(FacilityExternalVisitor facilityExternalVisitor);

	public int hashCode();

	public CacheModel<FacilityExternalVisitor> toCacheModel();

	public FacilityExternalVisitor toEscapedModel();

	public String toString();

	public String toXmlString();
}