/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.pacnet.connect.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the SAM_radacct service. Represents a row in the &quot;SAM_radacct&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.pacnet.connect.model.impl.SAM_radacctModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.pacnet.connect.model.impl.SAM_radacctImpl}.
 * </p>
 *
 * @author CloudSmartz
 * @see SAM_radacct
 * @see com.pacnet.connect.model.impl.SAM_radacctImpl
 * @see com.pacnet.connect.model.impl.SAM_radacctModelImpl
 * @generated
 */
public interface SAM_radacctModel extends BaseModel<SAM_radacct> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a s a m_radacct model instance should use the {@link SAM_radacct} interface instead.
	 */

	/**
	 * Returns the primary key of this s a m_radacct.
	 *
	 * @return the primary key of this s a m_radacct
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this s a m_radacct.
	 *
	 * @param primaryKey the primary key of this s a m_radacct
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the rad acct ID of this s a m_radacct.
	 *
	 * @return the rad acct ID of this s a m_radacct
	 */
	public long getRadAcctId();

	/**
	 * Sets the rad acct ID of this s a m_radacct.
	 *
	 * @param RadAcctId the rad acct ID of this s a m_radacct
	 */
	public void setRadAcctId(long RadAcctId);

	/**
	 * Returns the radcheck_id of this s a m_radacct.
	 *
	 * @return the radcheck_id of this s a m_radacct
	 */
	public long getRadcheck_id();

	/**
	 * Sets the radcheck_id of this s a m_radacct.
	 *
	 * @param radcheck_id the radcheck_id of this s a m_radacct
	 */
	public void setRadcheck_id(long radcheck_id);

	/**
	 * Returns the acct session ID of this s a m_radacct.
	 *
	 * @return the acct session ID of this s a m_radacct
	 */
	@AutoEscape
	public String getAcctSessionId();

	/**
	 * Sets the acct session ID of this s a m_radacct.
	 *
	 * @param AcctSessionId the acct session ID of this s a m_radacct
	 */
	public void setAcctSessionId(String AcctSessionId);

	/**
	 * Returns the acct unique ID of this s a m_radacct.
	 *
	 * @return the acct unique ID of this s a m_radacct
	 */
	@AutoEscape
	public String getAcctUniqueId();

	/**
	 * Sets the acct unique ID of this s a m_radacct.
	 *
	 * @param AcctUniqueId the acct unique ID of this s a m_radacct
	 */
	public void setAcctUniqueId(String AcctUniqueId);

	/**
	 * Returns the realm of this s a m_radacct.
	 *
	 * @return the realm of this s a m_radacct
	 */
	@AutoEscape
	public String getRealm();

	/**
	 * Sets the realm of this s a m_radacct.
	 *
	 * @param Realm the realm of this s a m_radacct
	 */
	public void setRealm(String Realm);

	/**
	 * Returns the n a s i p address of this s a m_radacct.
	 *
	 * @return the n a s i p address of this s a m_radacct
	 */
	@AutoEscape
	public String getNASIPAddress();

	/**
	 * Sets the n a s i p address of this s a m_radacct.
	 *
	 * @param NASIPAddress the n a s i p address of this s a m_radacct
	 */
	public void setNASIPAddress(String NASIPAddress);

	/**
	 * Returns the n a s port ID of this s a m_radacct.
	 *
	 * @return the n a s port ID of this s a m_radacct
	 */
	@AutoEscape
	public String getNASPortId();

	/**
	 * Sets the n a s port ID of this s a m_radacct.
	 *
	 * @param NASPortId the n a s port ID of this s a m_radacct
	 */
	public void setNASPortId(String NASPortId);

	/**
	 * Returns the n a s port type of this s a m_radacct.
	 *
	 * @return the n a s port type of this s a m_radacct
	 */
	@AutoEscape
	public String getNASPortType();

	/**
	 * Sets the n a s port type of this s a m_radacct.
	 *
	 * @param NASPortType the n a s port type of this s a m_radacct
	 */
	public void setNASPortType(String NASPortType);

	/**
	 * Returns the acct start time of this s a m_radacct.
	 *
	 * @return the acct start time of this s a m_radacct
	 */
	public Date getAcctStartTime();

	/**
	 * Sets the acct start time of this s a m_radacct.
	 *
	 * @param AcctStartTime the acct start time of this s a m_radacct
	 */
	public void setAcctStartTime(Date AcctStartTime);

	/**
	 * Returns the acct stop time of this s a m_radacct.
	 *
	 * @return the acct stop time of this s a m_radacct
	 */
	public Date getAcctStopTime();

	/**
	 * Sets the acct stop time of this s a m_radacct.
	 *
	 * @param AcctStopTime the acct stop time of this s a m_radacct
	 */
	public void setAcctStopTime(Date AcctStopTime);

	/**
	 * Returns the acct session time of this s a m_radacct.
	 *
	 * @return the acct session time of this s a m_radacct
	 */
	public long getAcctSessionTime();

	/**
	 * Sets the acct session time of this s a m_radacct.
	 *
	 * @param AcctSessionTime the acct session time of this s a m_radacct
	 */
	public void setAcctSessionTime(long AcctSessionTime);

	/**
	 * Returns the acct authentic of this s a m_radacct.
	 *
	 * @return the acct authentic of this s a m_radacct
	 */
	@AutoEscape
	public String getAcctAuthentic();

	/**
	 * Sets the acct authentic of this s a m_radacct.
	 *
	 * @param AcctAuthentic the acct authentic of this s a m_radacct
	 */
	public void setAcctAuthentic(String AcctAuthentic);

	/**
	 * Returns the connect info_start of this s a m_radacct.
	 *
	 * @return the connect info_start of this s a m_radacct
	 */
	@AutoEscape
	public String getConnectInfo_start();

	/**
	 * Sets the connect info_start of this s a m_radacct.
	 *
	 * @param ConnectInfo_start the connect info_start of this s a m_radacct
	 */
	public void setConnectInfo_start(String ConnectInfo_start);

	/**
	 * Returns the connect info_stop of this s a m_radacct.
	 *
	 * @return the connect info_stop of this s a m_radacct
	 */
	@AutoEscape
	public String getConnectInfo_stop();

	/**
	 * Sets the connect info_stop of this s a m_radacct.
	 *
	 * @param ConnectInfo_stop the connect info_stop of this s a m_radacct
	 */
	public void setConnectInfo_stop(String ConnectInfo_stop);

	/**
	 * Returns the acct input octets of this s a m_radacct.
	 *
	 * @return the acct input octets of this s a m_radacct
	 */
	public long getAcctInputOctets();

	/**
	 * Sets the acct input octets of this s a m_radacct.
	 *
	 * @param AcctInputOctets the acct input octets of this s a m_radacct
	 */
	public void setAcctInputOctets(long AcctInputOctets);

	/**
	 * Returns the acct output octets of this s a m_radacct.
	 *
	 * @return the acct output octets of this s a m_radacct
	 */
	public long getAcctOutputOctets();

	/**
	 * Sets the acct output octets of this s a m_radacct.
	 *
	 * @param AcctOutputOctets the acct output octets of this s a m_radacct
	 */
	public void setAcctOutputOctets(long AcctOutputOctets);

	/**
	 * Returns the called station ID of this s a m_radacct.
	 *
	 * @return the called station ID of this s a m_radacct
	 */
	@AutoEscape
	public String getCalledStationId();

	/**
	 * Sets the called station ID of this s a m_radacct.
	 *
	 * @param CalledStationId the called station ID of this s a m_radacct
	 */
	public void setCalledStationId(String CalledStationId);

	/**
	 * Returns the calling station ID of this s a m_radacct.
	 *
	 * @return the calling station ID of this s a m_radacct
	 */
	@AutoEscape
	public String getCallingStationId();

	/**
	 * Sets the calling station ID of this s a m_radacct.
	 *
	 * @param CallingStationId the calling station ID of this s a m_radacct
	 */
	public void setCallingStationId(String CallingStationId);

	/**
	 * Returns the acctterminate cause of this s a m_radacct.
	 *
	 * @return the acctterminate cause of this s a m_radacct
	 */
	@AutoEscape
	public String getAcctterminateCause();

	/**
	 * Sets the acctterminate cause of this s a m_radacct.
	 *
	 * @param AcctterminateCause the acctterminate cause of this s a m_radacct
	 */
	public void setAcctterminateCause(String AcctterminateCause);

	/**
	 * Returns the service typr of this s a m_radacct.
	 *
	 * @return the service typr of this s a m_radacct
	 */
	@AutoEscape
	public String getServiceTypr();

	/**
	 * Sets the service typr of this s a m_radacct.
	 *
	 * @param ServiceTypr the service typr of this s a m_radacct
	 */
	public void setServiceTypr(String ServiceTypr);

	/**
	 * Returns the framed protocol of this s a m_radacct.
	 *
	 * @return the framed protocol of this s a m_radacct
	 */
	@AutoEscape
	public String getFramedProtocol();

	/**
	 * Sets the framed protocol of this s a m_radacct.
	 *
	 * @param FramedProtocol the framed protocol of this s a m_radacct
	 */
	public void setFramedProtocol(String FramedProtocol);

	/**
	 * Returns the framed i p address of this s a m_radacct.
	 *
	 * @return the framed i p address of this s a m_radacct
	 */
	@AutoEscape
	public String getFramedIPAddress();

	/**
	 * Sets the framed i p address of this s a m_radacct.
	 *
	 * @param FramedIPAddress the framed i p address of this s a m_radacct
	 */
	public void setFramedIPAddress(String FramedIPAddress);

	/**
	 * Returns the acct start delay of this s a m_radacct.
	 *
	 * @return the acct start delay of this s a m_radacct
	 */
	public long getAcctStartDelay();

	/**
	 * Sets the acct start delay of this s a m_radacct.
	 *
	 * @param AcctStartDelay the acct start delay of this s a m_radacct
	 */
	public void setAcctStartDelay(long AcctStartDelay);

	/**
	 * Returns the acct stop delay of this s a m_radacct.
	 *
	 * @return the acct stop delay of this s a m_radacct
	 */
	public long getAcctStopDelay();

	/**
	 * Sets the acct stop delay of this s a m_radacct.
	 *
	 * @param AcctStopDelay the acct stop delay of this s a m_radacct
	 */
	public void setAcctStopDelay(long AcctStopDelay);

	/**
	 * Returns the is active of this s a m_radacct.
	 *
	 * @return the is active of this s a m_radacct
	 */
	public int getIsActive();

	/**
	 * Sets the is active of this s a m_radacct.
	 *
	 * @param IsActive the is active of this s a m_radacct
	 */
	public void setIsActive(int IsActive);

	/**
	 * Returns the created_ on of this s a m_radacct.
	 *
	 * @return the created_ on of this s a m_radacct
	 */
	public Date getCreated_On();

	/**
	 * Sets the created_ on of this s a m_radacct.
	 *
	 * @param Created_On the created_ on of this s a m_radacct
	 */
	public void setCreated_On(Date Created_On);

	/**
	 * Returns the created_ by of this s a m_radacct.
	 *
	 * @return the created_ by of this s a m_radacct
	 */
	@AutoEscape
	public String getCreated_By();

	/**
	 * Sets the created_ by of this s a m_radacct.
	 *
	 * @param Created_By the created_ by of this s a m_radacct
	 */
	public void setCreated_By(String Created_By);

	/**
	 * Returns the updated_ on of this s a m_radacct.
	 *
	 * @return the updated_ on of this s a m_radacct
	 */
	public Date getUpdated_On();

	/**
	 * Sets the updated_ on of this s a m_radacct.
	 *
	 * @param Updated_On the updated_ on of this s a m_radacct
	 */
	public void setUpdated_On(Date Updated_On);

	/**
	 * Returns the updated_ by of this s a m_radacct.
	 *
	 * @return the updated_ by of this s a m_radacct
	 */
	@AutoEscape
	public String getUpdated_By();

	/**
	 * Sets the updated_ by of this s a m_radacct.
	 *
	 * @param Updated_By the updated_ by of this s a m_radacct
	 */
	public void setUpdated_By(String Updated_By);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(SAM_radacct sam_radacct);

	public int hashCode();

	public CacheModel<SAM_radacct> toCacheModel();

	public SAM_radacct toEscapedModel();

	public String toString();

	public String toXmlString();
}