/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.pacnet.connect.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the SAM_reservation service. Represents a row in the &quot;SAM_reservation&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.pacnet.connect.model.impl.SAM_reservationModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.pacnet.connect.model.impl.SAM_reservationImpl}.
 * </p>
 *
 * @author CloudSmartz
 * @see SAM_reservation
 * @see com.pacnet.connect.model.impl.SAM_reservationImpl
 * @see com.pacnet.connect.model.impl.SAM_reservationModelImpl
 * @generated
 */
public interface SAM_reservationModel extends BaseModel<SAM_reservation> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a s a m_reservation model instance should use the {@link SAM_reservation} interface instead.
	 */

	/**
	 * Returns the primary key of this s a m_reservation.
	 *
	 * @return the primary key of this s a m_reservation
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this s a m_reservation.
	 *
	 * @param primaryKey the primary key of this s a m_reservation
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this s a m_reservation.
	 *
	 * @return the ID of this s a m_reservation
	 */
	public long getId();

	/**
	 * Sets the ID of this s a m_reservation.
	 *
	 * @param id the ID of this s a m_reservation
	 */
	public void setId(long id);

	/**
	 * Returns the name of this s a m_reservation.
	 *
	 * @return the name of this s a m_reservation
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this s a m_reservation.
	 *
	 * @param name the name of this s a m_reservation
	 */
	public void setName(String name);

	/**
	 * Returns the start date of this s a m_reservation.
	 *
	 * @return the start date of this s a m_reservation
	 */
	public Date getStartDate();

	/**
	 * Sets the start date of this s a m_reservation.
	 *
	 * @param startDate the start date of this s a m_reservation
	 */
	public void setStartDate(Date startDate);

	/**
	 * Returns the end date of this s a m_reservation.
	 *
	 * @return the end date of this s a m_reservation
	 */
	public Date getEndDate();

	/**
	 * Sets the end date of this s a m_reservation.
	 *
	 * @param endDate the end date of this s a m_reservation
	 */
	public void setEndDate(Date endDate);

	/**
	 * Returns the owner of this s a m_reservation.
	 *
	 * @return the owner of this s a m_reservation
	 */
	@AutoEscape
	public String getOwner();

	/**
	 * Sets the owner of this s a m_reservation.
	 *
	 * @param owner the owner of this s a m_reservation
	 */
	public void setOwner(String owner);

	/**
	 * Returns the provision of this s a m_reservation.
	 *
	 * @return the provision of this s a m_reservation
	 */
	public int getProvision();

	/**
	 * Sets the provision of this s a m_reservation.
	 *
	 * @param provision the provision of this s a m_reservation
	 */
	public void setProvision(int provision);

	/**
	 * Returns the is active of this s a m_reservation.
	 *
	 * @return the is active of this s a m_reservation
	 */
	public int getIsActive();

	/**
	 * Sets the is active of this s a m_reservation.
	 *
	 * @param IsActive the is active of this s a m_reservation
	 */
	public void setIsActive(int IsActive);

	/**
	 * Returns the created_ on of this s a m_reservation.
	 *
	 * @return the created_ on of this s a m_reservation
	 */
	public Date getCreated_On();

	/**
	 * Sets the created_ on of this s a m_reservation.
	 *
	 * @param Created_On the created_ on of this s a m_reservation
	 */
	public void setCreated_On(Date Created_On);

	/**
	 * Returns the created_ by of this s a m_reservation.
	 *
	 * @return the created_ by of this s a m_reservation
	 */
	@AutoEscape
	public String getCreated_By();

	/**
	 * Sets the created_ by of this s a m_reservation.
	 *
	 * @param Created_By the created_ by of this s a m_reservation
	 */
	public void setCreated_By(String Created_By);

	/**
	 * Returns the updated_ on of this s a m_reservation.
	 *
	 * @return the updated_ on of this s a m_reservation
	 */
	public Date getUpdated_On();

	/**
	 * Sets the updated_ on of this s a m_reservation.
	 *
	 * @param Updated_On the updated_ on of this s a m_reservation
	 */
	public void setUpdated_On(Date Updated_On);

	/**
	 * Returns the updated_ by of this s a m_reservation.
	 *
	 * @return the updated_ by of this s a m_reservation
	 */
	@AutoEscape
	public String getUpdated_By();

	/**
	 * Sets the updated_ by of this s a m_reservation.
	 *
	 * @param Updated_By the updated_ by of this s a m_reservation
	 */
	public void setUpdated_By(String Updated_By);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(SAM_reservation sam_reservation);

	public int hashCode();

	public CacheModel<SAM_reservation> toCacheModel();

	public SAM_reservation toEscapedModel();

	public String toString();

	public String toXmlString();
}