/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.pacnet.connect.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the SAM_Email_History service. Represents a row in the &quot;SAM_Email_History&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.pacnet.connect.model.impl.SAM_Email_HistoryModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.pacnet.connect.model.impl.SAM_Email_HistoryImpl}.
 * </p>
 *
 * @author CloudSmartz
 * @see SAM_Email_History
 * @see com.pacnet.connect.model.impl.SAM_Email_HistoryImpl
 * @see com.pacnet.connect.model.impl.SAM_Email_HistoryModelImpl
 * @generated
 */
public interface SAM_Email_HistoryModel extends BaseModel<SAM_Email_History> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a s a m_ email_ history model instance should use the {@link SAM_Email_History} interface instead.
	 */

	/**
	 * Returns the primary key of this s a m_ email_ history.
	 *
	 * @return the primary key of this s a m_ email_ history
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this s a m_ email_ history.
	 *
	 * @param primaryKey the primary key of this s a m_ email_ history
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this s a m_ email_ history.
	 *
	 * @return the ID of this s a m_ email_ history
	 */
	public long getId();

	/**
	 * Sets the ID of this s a m_ email_ history.
	 *
	 * @param id the ID of this s a m_ email_ history
	 */
	public void setId(long id);

	/**
	 * Returns the name of this s a m_ email_ history.
	 *
	 * @return the name of this s a m_ email_ history
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this s a m_ email_ history.
	 *
	 * @param name the name of this s a m_ email_ history
	 */
	public void setName(String name);

	/**
	 * Returns the history type of this s a m_ email_ history.
	 *
	 * @return the history type of this s a m_ email_ history
	 */
	public int getHistoryType();

	/**
	 * Sets the history type of this s a m_ email_ history.
	 *
	 * @param historyType the history type of this s a m_ email_ history
	 */
	public void setHistoryType(int historyType);

	/**
	 * Returns the email from of this s a m_ email_ history.
	 *
	 * @return the email from of this s a m_ email_ history
	 */
	@AutoEscape
	public String getEmailFrom();

	/**
	 * Sets the email from of this s a m_ email_ history.
	 *
	 * @param emailFrom the email from of this s a m_ email_ history
	 */
	public void setEmailFrom(String emailFrom);

	/**
	 * Returns the email to of this s a m_ email_ history.
	 *
	 * @return the email to of this s a m_ email_ history
	 */
	@AutoEscape
	public String getEmailTo();

	/**
	 * Sets the email to of this s a m_ email_ history.
	 *
	 * @param emailTo the email to of this s a m_ email_ history
	 */
	public void setEmailTo(String emailTo);

	/**
	 * Returns the email title of this s a m_ email_ history.
	 *
	 * @return the email title of this s a m_ email_ history
	 */
	@AutoEscape
	public String getEmailTitle();

	/**
	 * Sets the email title of this s a m_ email_ history.
	 *
	 * @param emailTitle the email title of this s a m_ email_ history
	 */
	public void setEmailTitle(String emailTitle);

	/**
	 * Returns the email content of this s a m_ email_ history.
	 *
	 * @return the email content of this s a m_ email_ history
	 */
	@AutoEscape
	public String getEmailContent();

	/**
	 * Sets the email content of this s a m_ email_ history.
	 *
	 * @param emailContent the email content of this s a m_ email_ history
	 */
	public void setEmailContent(String emailContent);

	/**
	 * Returns the is active of this s a m_ email_ history.
	 *
	 * @return the is active of this s a m_ email_ history
	 */
	public int getIsActive();

	/**
	 * Sets the is active of this s a m_ email_ history.
	 *
	 * @param IsActive the is active of this s a m_ email_ history
	 */
	public void setIsActive(int IsActive);

	/**
	 * Returns the created_ on of this s a m_ email_ history.
	 *
	 * @return the created_ on of this s a m_ email_ history
	 */
	public Date getCreated_On();

	/**
	 * Sets the created_ on of this s a m_ email_ history.
	 *
	 * @param Created_On the created_ on of this s a m_ email_ history
	 */
	public void setCreated_On(Date Created_On);

	/**
	 * Returns the created_ by of this s a m_ email_ history.
	 *
	 * @return the created_ by of this s a m_ email_ history
	 */
	@AutoEscape
	public String getCreated_By();

	/**
	 * Sets the created_ by of this s a m_ email_ history.
	 *
	 * @param Created_By the created_ by of this s a m_ email_ history
	 */
	public void setCreated_By(String Created_By);

	/**
	 * Returns the updated_ on of this s a m_ email_ history.
	 *
	 * @return the updated_ on of this s a m_ email_ history
	 */
	public Date getUpdated_On();

	/**
	 * Sets the updated_ on of this s a m_ email_ history.
	 *
	 * @param Updated_On the updated_ on of this s a m_ email_ history
	 */
	public void setUpdated_On(Date Updated_On);

	/**
	 * Returns the updated_ by of this s a m_ email_ history.
	 *
	 * @return the updated_ by of this s a m_ email_ history
	 */
	@AutoEscape
	public String getUpdated_By();

	/**
	 * Sets the updated_ by of this s a m_ email_ history.
	 *
	 * @param Updated_By the updated_ by of this s a m_ email_ history
	 */
	public void setUpdated_By(String Updated_By);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(SAM_Email_History sam_Email_History);

	public int hashCode();

	public CacheModel<SAM_Email_History> toCacheModel();

	public SAM_Email_History toEscapedModel();

	public String toString();

	public String toXmlString();
}