/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.pacnet.connect.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the SAM_radcheck service. Represents a row in the &quot;SAM_radcheck&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.pacnet.connect.model.impl.SAM_radcheckModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.pacnet.connect.model.impl.SAM_radcheckImpl}.
 * </p>
 *
 * @author CloudSmartz
 * @see SAM_radcheck
 * @see com.pacnet.connect.model.impl.SAM_radcheckImpl
 * @see com.pacnet.connect.model.impl.SAM_radcheckModelImpl
 * @generated
 */
public interface SAM_radcheckModel extends BaseModel<SAM_radcheck> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a s a m_radcheck model instance should use the {@link SAM_radcheck} interface instead.
	 */

	/**
	 * Returns the primary key of this s a m_radcheck.
	 *
	 * @return the primary key of this s a m_radcheck
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this s a m_radcheck.
	 *
	 * @param primaryKey the primary key of this s a m_radcheck
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this s a m_radcheck.
	 *
	 * @return the ID of this s a m_radcheck
	 */
	public long getId();

	/**
	 * Sets the ID of this s a m_radcheck.
	 *
	 * @param id the ID of this s a m_radcheck
	 */
	public void setId(long id);

	/**
	 * Returns the company_id of this s a m_radcheck.
	 *
	 * @return the company_id of this s a m_radcheck
	 */
	public long getCompany_id();

	/**
	 * Sets the company_id of this s a m_radcheck.
	 *
	 * @param company_id the company_id of this s a m_radcheck
	 */
	public void setCompany_id(long company_id);

	/**
	 * Returns the username of this s a m_radcheck.
	 *
	 * @return the username of this s a m_radcheck
	 */
	@AutoEscape
	public String getUsername();

	/**
	 * Sets the username of this s a m_radcheck.
	 *
	 * @param username the username of this s a m_radcheck
	 */
	public void setUsername(String username);

	/**
	 * Returns the attribute of this s a m_radcheck.
	 *
	 * @return the attribute of this s a m_radcheck
	 */
	@AutoEscape
	public String getAttribute();

	/**
	 * Sets the attribute of this s a m_radcheck.
	 *
	 * @param attribute the attribute of this s a m_radcheck
	 */
	public void setAttribute(String attribute);

	/**
	 * Returns the op of this s a m_radcheck.
	 *
	 * @return the op of this s a m_radcheck
	 */
	@AutoEscape
	public String getOp();

	/**
	 * Sets the op of this s a m_radcheck.
	 *
	 * @param op the op of this s a m_radcheck
	 */
	public void setOp(String op);

	/**
	 * Returns the value of this s a m_radcheck.
	 *
	 * @return the value of this s a m_radcheck
	 */
	@AutoEscape
	public String getValue();

	/**
	 * Sets the value of this s a m_radcheck.
	 *
	 * @param value the value of this s a m_radcheck
	 */
	public void setValue(String value);

	/**
	 * Returns the is admin of this s a m_radcheck.
	 *
	 * @return the is admin of this s a m_radcheck
	 */
	public int getIsAdmin();

	/**
	 * Sets the is admin of this s a m_radcheck.
	 *
	 * @param IsAdmin the is admin of this s a m_radcheck
	 */
	public void setIsAdmin(int IsAdmin);

	/**
	 * Returns the is active of this s a m_radcheck.
	 *
	 * @return the is active of this s a m_radcheck
	 */
	public int getIsActive();

	/**
	 * Sets the is active of this s a m_radcheck.
	 *
	 * @param IsActive the is active of this s a m_radcheck
	 */
	public void setIsActive(int IsActive);

	/**
	 * Returns the created_ on of this s a m_radcheck.
	 *
	 * @return the created_ on of this s a m_radcheck
	 */
	public Date getCreated_On();

	/**
	 * Sets the created_ on of this s a m_radcheck.
	 *
	 * @param Created_On the created_ on of this s a m_radcheck
	 */
	public void setCreated_On(Date Created_On);

	/**
	 * Returns the created_ by of this s a m_radcheck.
	 *
	 * @return the created_ by of this s a m_radcheck
	 */
	@AutoEscape
	public String getCreated_By();

	/**
	 * Sets the created_ by of this s a m_radcheck.
	 *
	 * @param Created_By the created_ by of this s a m_radcheck
	 */
	public void setCreated_By(String Created_By);

	/**
	 * Returns the updated_ on of this s a m_radcheck.
	 *
	 * @return the updated_ on of this s a m_radcheck
	 */
	public Date getUpdated_On();

	/**
	 * Sets the updated_ on of this s a m_radcheck.
	 *
	 * @param Updated_On the updated_ on of this s a m_radcheck
	 */
	public void setUpdated_On(Date Updated_On);

	/**
	 * Returns the updated_ by of this s a m_radcheck.
	 *
	 * @return the updated_ by of this s a m_radcheck
	 */
	@AutoEscape
	public String getUpdated_By();

	/**
	 * Sets the updated_ by of this s a m_radcheck.
	 *
	 * @param Updated_By the updated_ by of this s a m_radcheck
	 */
	public void setUpdated_By(String Updated_By);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(SAM_radcheck sam_radcheck);

	public int hashCode();

	public CacheModel<SAM_radcheck> toCacheModel();

	public SAM_radcheck toEscapedModel();

	public String toString();

	public String toXmlString();
}