/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.pacnet.connect.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the SAM_admins service. Represents a row in the &quot;SAM_admins&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.pacnet.connect.model.impl.SAM_adminsModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.pacnet.connect.model.impl.SAM_adminsImpl}.
 * </p>
 *
 * @author CloudSmartz
 * @see SAM_admins
 * @see com.pacnet.connect.model.impl.SAM_adminsImpl
 * @see com.pacnet.connect.model.impl.SAM_adminsModelImpl
 * @generated
 */
public interface SAM_adminsModel extends BaseModel<SAM_admins> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a s a m_admins model instance should use the {@link SAM_admins} interface instead.
	 */

	/**
	 * Returns the primary key of this s a m_admins.
	 *
	 * @return the primary key of this s a m_admins
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this s a m_admins.
	 *
	 * @param primaryKey the primary key of this s a m_admins
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this s a m_admins.
	 *
	 * @return the ID of this s a m_admins
	 */
	public long getId();

	/**
	 * Sets the ID of this s a m_admins.
	 *
	 * @param id the ID of this s a m_admins
	 */
	public void setId(long id);

	/**
	 * Returns the user_id of this s a m_admins.
	 *
	 * @return the user_id of this s a m_admins
	 */
	public long getUser_id();

	/**
	 * Sets the user_id of this s a m_admins.
	 *
	 * @param user_id the user_id of this s a m_admins
	 */
	public void setUser_id(long user_id);

	/**
	 * Returns the radcheck_id of this s a m_admins.
	 *
	 * @return the radcheck_id of this s a m_admins
	 */
	public long getRadcheck_id();

	/**
	 * Sets the radcheck_id of this s a m_admins.
	 *
	 * @param radcheck_id the radcheck_id of this s a m_admins
	 */
	public void setRadcheck_id(long radcheck_id);

	/**
	 * Returns the company_id of this s a m_admins.
	 *
	 * @return the company_id of this s a m_admins
	 */
	public long getCompany_id();

	/**
	 * Sets the company_id of this s a m_admins.
	 *
	 * @param company_id the company_id of this s a m_admins
	 */
	public void setCompany_id(long company_id);

	/**
	 * Returns the is active of this s a m_admins.
	 *
	 * @return the is active of this s a m_admins
	 */
	public int getIsActive();

	/**
	 * Sets the is active of this s a m_admins.
	 *
	 * @param IsActive the is active of this s a m_admins
	 */
	public void setIsActive(int IsActive);

	/**
	 * Returns the created_ on of this s a m_admins.
	 *
	 * @return the created_ on of this s a m_admins
	 */
	public Date getCreated_On();

	/**
	 * Sets the created_ on of this s a m_admins.
	 *
	 * @param Created_On the created_ on of this s a m_admins
	 */
	public void setCreated_On(Date Created_On);

	/**
	 * Returns the created_ by of this s a m_admins.
	 *
	 * @return the created_ by of this s a m_admins
	 */
	@AutoEscape
	public String getCreated_By();

	/**
	 * Sets the created_ by of this s a m_admins.
	 *
	 * @param Created_By the created_ by of this s a m_admins
	 */
	public void setCreated_By(String Created_By);

	/**
	 * Returns the updated_ on of this s a m_admins.
	 *
	 * @return the updated_ on of this s a m_admins
	 */
	public Date getUpdated_On();

	/**
	 * Sets the updated_ on of this s a m_admins.
	 *
	 * @param Updated_On the updated_ on of this s a m_admins
	 */
	public void setUpdated_On(Date Updated_On);

	/**
	 * Returns the updated_ by of this s a m_admins.
	 *
	 * @return the updated_ by of this s a m_admins
	 */
	@AutoEscape
	public String getUpdated_By();

	/**
	 * Sets the updated_ by of this s a m_admins.
	 *
	 * @param Updated_By the updated_ by of this s a m_admins
	 */
	public void setUpdated_By(String Updated_By);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(SAM_admins sam_admins);

	public int hashCode();

	public CacheModel<SAM_admins> toCacheModel();

	public SAM_admins toEscapedModel();

	public String toString();

	public String toXmlString();
}