/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.pacnet.connect.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the SMAAdmins service. Represents a row in the &quot;PA_SMA_admins&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.pacnet.connect.model.impl.SMAAdminsModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.pacnet.connect.model.impl.SMAAdminsImpl}.
 * </p>
 *
 * @author CloudSmartz
 * @see SMAAdmins
 * @see com.pacnet.connect.model.impl.SMAAdminsImpl
 * @see com.pacnet.connect.model.impl.SMAAdminsModelImpl
 * @generated
 */
public interface SMAAdminsModel extends BaseModel<SMAAdmins> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a s m a admins model instance should use the {@link SMAAdmins} interface instead.
	 */

	/**
	 * Returns the primary key of this s m a admins.
	 *
	 * @return the primary key of this s m a admins
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this s m a admins.
	 *
	 * @param primaryKey the primary key of this s m a admins
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this s m a admins.
	 *
	 * @return the ID of this s m a admins
	 */
	public long getId();

	/**
	 * Sets the ID of this s m a admins.
	 *
	 * @param id the ID of this s m a admins
	 */
	public void setId(long id);

	/**
	 * Returns the user ID of this s m a admins.
	 *
	 * @return the user ID of this s m a admins
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this s m a admins.
	 *
	 * @param userId the user ID of this s m a admins
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this s m a admins.
	 *
	 * @return the user uuid of this s m a admins
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this s m a admins.
	 *
	 * @param userUuid the user uuid of this s m a admins
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the radcheck ID of this s m a admins.
	 *
	 * @return the radcheck ID of this s m a admins
	 */
	public long getRadcheckId();

	/**
	 * Sets the radcheck ID of this s m a admins.
	 *
	 * @param radcheckId the radcheck ID of this s m a admins
	 */
	public void setRadcheckId(long radcheckId);

	/**
	 * Returns the company ID of this s m a admins.
	 *
	 * @return the company ID of this s m a admins
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this s m a admins.
	 *
	 * @param companyId the company ID of this s m a admins
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the is active of this s m a admins.
	 *
	 * @return the is active of this s m a admins
	 */
	public int getIsActive();

	/**
	 * Sets the is active of this s m a admins.
	 *
	 * @param isActive the is active of this s m a admins
	 */
	public void setIsActive(int isActive);

	/**
	 * Returns the created on of this s m a admins.
	 *
	 * @return the created on of this s m a admins
	 */
	public Date getCreatedOn();

	/**
	 * Sets the created on of this s m a admins.
	 *
	 * @param createdOn the created on of this s m a admins
	 */
	public void setCreatedOn(Date createdOn);

	/**
	 * Returns the created by of this s m a admins.
	 *
	 * @return the created by of this s m a admins
	 */
	@AutoEscape
	public String getCreatedBy();

	/**
	 * Sets the created by of this s m a admins.
	 *
	 * @param createdBy the created by of this s m a admins
	 */
	public void setCreatedBy(String createdBy);

	/**
	 * Returns the updated on of this s m a admins.
	 *
	 * @return the updated on of this s m a admins
	 */
	public Date getUpdatedOn();

	/**
	 * Sets the updated on of this s m a admins.
	 *
	 * @param updatedOn the updated on of this s m a admins
	 */
	public void setUpdatedOn(Date updatedOn);

	/**
	 * Returns the updated by of this s m a admins.
	 *
	 * @return the updated by of this s m a admins
	 */
	@AutoEscape
	public String getUpdatedBy();

	/**
	 * Sets the updated by of this s m a admins.
	 *
	 * @param updatedBy the updated by of this s m a admins
	 */
	public void setUpdatedBy(String updatedBy);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(SMAAdmins smaAdmins);

	public int hashCode();

	public CacheModel<SMAAdmins> toCacheModel();

	public SMAAdmins toEscapedModel();

	public String toString();

	public String toXmlString();
}