/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.pacnet.connect.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the SMACompanyList service. Represents a row in the &quot;v_i_sma_user_details&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.pacnet.connect.model.impl.SMACompanyListModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.pacnet.connect.model.impl.SMACompanyListImpl}.
 * </p>
 *
 * @author CloudSmartz
 * @see SMACompanyList
 * @see com.pacnet.connect.model.impl.SMACompanyListImpl
 * @see com.pacnet.connect.model.impl.SMACompanyListModelImpl
 * @generated
 */
public interface SMACompanyListModel extends BaseModel<SMACompanyList> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a s m a company list model instance should use the {@link SMACompanyList} interface instead.
	 */

	/**
	 * Returns the primary key of this s m a company list.
	 *
	 * @return the primary key of this s m a company list
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this s m a company list.
	 *
	 * @param primaryKey the primary key of this s m a company list
	 */
	public void setPrimaryKey(String primaryKey);

	/**
	 * Returns the ID of this s m a company list.
	 *
	 * @return the ID of this s m a company list
	 */
	@AutoEscape
	public String getId();

	/**
	 * Sets the ID of this s m a company list.
	 *
	 * @param id the ID of this s m a company list
	 */
	public void setId(String id);

	/**
	 * Returns the admin user ID of this s m a company list.
	 *
	 * @return the admin user ID of this s m a company list
	 */
	public long getAdminUserId();

	/**
	 * Sets the admin user ID of this s m a company list.
	 *
	 * @param adminUserId the admin user ID of this s m a company list
	 */
	public void setAdminUserId(long adminUserId);

	/**
	 * Returns the admin user uuid of this s m a company list.
	 *
	 * @return the admin user uuid of this s m a company list
	 * @throws SystemException if a system exception occurred
	 */
	public String getAdminUserUuid() throws SystemException;

	/**
	 * Sets the admin user uuid of this s m a company list.
	 *
	 * @param adminUserUuid the admin user uuid of this s m a company list
	 */
	public void setAdminUserUuid(String adminUserUuid);

	/**
	 * Returns the company ID of this s m a company list.
	 *
	 * @return the company ID of this s m a company list
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this s m a company list.
	 *
	 * @param companyId the company ID of this s m a company list
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the customer ID of this s m a company list.
	 *
	 * @return the customer ID of this s m a company list
	 */
	public long getCustomerId();

	/**
	 * Sets the customer ID of this s m a company list.
	 *
	 * @param customerId the customer ID of this s m a company list
	 */
	public void setCustomerId(long customerId);

	/**
	 * Returns the domains of this s m a company list.
	 *
	 * @return the domains of this s m a company list
	 */
	@AutoEscape
	public String getDomains();

	/**
	 * Sets the domains of this s m a company list.
	 *
	 * @param domains the domains of this s m a company list
	 */
	public void setDomains(String domains);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(SMACompanyList smaCompanyList);

	public int hashCode();

	public CacheModel<SMACompanyList> toCacheModel();

	public SMACompanyList toEscapedModel();

	public String toString();

	public String toXmlString();
}