/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.pacnet.connect.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the SMACompanies service. Represents a row in the &quot;PA_SMA_companies&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.pacnet.connect.model.impl.SMACompaniesModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.pacnet.connect.model.impl.SMACompaniesImpl}.
 * </p>
 *
 * @author CloudSmartz
 * @see SMACompanies
 * @see com.pacnet.connect.model.impl.SMACompaniesImpl
 * @see com.pacnet.connect.model.impl.SMACompaniesModelImpl
 * @generated
 */
public interface SMACompaniesModel extends BaseModel<SMACompanies> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a s m a companies model instance should use the {@link SMACompanies} interface instead.
	 */

	/**
	 * Returns the primary key of this s m a companies.
	 *
	 * @return the primary key of this s m a companies
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this s m a companies.
	 *
	 * @param primaryKey the primary key of this s m a companies
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this s m a companies.
	 *
	 * @return the ID of this s m a companies
	 */
	public long getId();

	/**
	 * Sets the ID of this s m a companies.
	 *
	 * @param id the ID of this s m a companies
	 */
	public void setId(long id);

	/**
	 * Returns the customer ID of this s m a companies.
	 *
	 * @return the customer ID of this s m a companies
	 */
	public long getCustomerId();

	/**
	 * Sets the customer ID of this s m a companies.
	 *
	 * @param customerId the customer ID of this s m a companies
	 */
	public void setCustomerId(long customerId);

	/**
	 * Returns the company name of this s m a companies.
	 *
	 * @return the company name of this s m a companies
	 */
	@AutoEscape
	public String getCompanyName();

	/**
	 * Sets the company name of this s m a companies.
	 *
	 * @param companyName the company name of this s m a companies
	 */
	public void setCompanyName(String companyName);

	/**
	 * Returns the domains of this s m a companies.
	 *
	 * @return the domains of this s m a companies
	 */
	@AutoEscape
	public String getDomains();

	/**
	 * Sets the domains of this s m a companies.
	 *
	 * @param domains the domains of this s m a companies
	 */
	public void setDomains(String domains);

	/**
	 * Returns the group name of this s m a companies.
	 *
	 * @return the group name of this s m a companies
	 */
	@AutoEscape
	public String getGroupName();

	/**
	 * Sets the group name of this s m a companies.
	 *
	 * @param groupName the group name of this s m a companies
	 */
	public void setGroupName(String groupName);

	/**
	 * Returns the attribute of this s m a companies.
	 *
	 * @return the attribute of this s m a companies
	 */
	@AutoEscape
	public String getAttribute();

	/**
	 * Sets the attribute of this s m a companies.
	 *
	 * @param attribute the attribute of this s m a companies
	 */
	public void setAttribute(String attribute);

	/**
	 * Returns the op of this s m a companies.
	 *
	 * @return the op of this s m a companies
	 */
	@AutoEscape
	public String getOp();

	/**
	 * Sets the op of this s m a companies.
	 *
	 * @param op the op of this s m a companies
	 */
	public void setOp(String op);

	/**
	 * Returns the value of this s m a companies.
	 *
	 * @return the value of this s m a companies
	 */
	@AutoEscape
	public String getValue();

	/**
	 * Sets the value of this s m a companies.
	 *
	 * @param value the value of this s m a companies
	 */
	public void setValue(String value);

	/**
	 * Returns the max user of this s m a companies.
	 *
	 * @return the max user of this s m a companies
	 */
	public int getMaxUser();

	/**
	 * Sets the max user of this s m a companies.
	 *
	 * @param maxUser the max user of this s m a companies
	 */
	public void setMaxUser(int maxUser);

	/**
	 * Returns the is active of this s m a companies.
	 *
	 * @return the is active of this s m a companies
	 */
	public int getIsActive();

	/**
	 * Sets the is active of this s m a companies.
	 *
	 * @param isActive the is active of this s m a companies
	 */
	public void setIsActive(int isActive);

	/**
	 * Returns the created on of this s m a companies.
	 *
	 * @return the created on of this s m a companies
	 */
	public Date getCreatedOn();

	/**
	 * Sets the created on of this s m a companies.
	 *
	 * @param createdOn the created on of this s m a companies
	 */
	public void setCreatedOn(Date createdOn);

	/**
	 * Returns the created by of this s m a companies.
	 *
	 * @return the created by of this s m a companies
	 */
	@AutoEscape
	public String getCreatedBy();

	/**
	 * Sets the created by of this s m a companies.
	 *
	 * @param createdBy the created by of this s m a companies
	 */
	public void setCreatedBy(String createdBy);

	/**
	 * Returns the updated on of this s m a companies.
	 *
	 * @return the updated on of this s m a companies
	 */
	public Date getUpdatedOn();

	/**
	 * Sets the updated on of this s m a companies.
	 *
	 * @param updatedOn the updated on of this s m a companies
	 */
	public void setUpdatedOn(Date updatedOn);

	/**
	 * Returns the updated by of this s m a companies.
	 *
	 * @return the updated by of this s m a companies
	 */
	@AutoEscape
	public String getUpdatedBy();

	/**
	 * Sets the updated by of this s m a companies.
	 *
	 * @param updatedBy the updated by of this s m a companies
	 */
	public void setUpdatedBy(String updatedBy);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(SMACompanies smaCompanies);

	public int hashCode();

	public CacheModel<SMACompanies> toCacheModel();

	public SMACompanies toEscapedModel();

	public String toString();

	public String toXmlString();
}