/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.pacnet.connect.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the SMAEmailHistory service. Represents a row in the &quot;PA_SMA_Email_History&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.pacnet.connect.model.impl.SMAEmailHistoryModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.pacnet.connect.model.impl.SMAEmailHistoryImpl}.
 * </p>
 *
 * @author CloudSmartz
 * @see SMAEmailHistory
 * @see com.pacnet.connect.model.impl.SMAEmailHistoryImpl
 * @see com.pacnet.connect.model.impl.SMAEmailHistoryModelImpl
 * @generated
 */
public interface SMAEmailHistoryModel extends BaseModel<SMAEmailHistory> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a s m a email history model instance should use the {@link SMAEmailHistory} interface instead.
	 */

	/**
	 * Returns the primary key of this s m a email history.
	 *
	 * @return the primary key of this s m a email history
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this s m a email history.
	 *
	 * @param primaryKey the primary key of this s m a email history
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this s m a email history.
	 *
	 * @return the ID of this s m a email history
	 */
	public long getId();

	/**
	 * Sets the ID of this s m a email history.
	 *
	 * @param id the ID of this s m a email history
	 */
	public void setId(long id);

	/**
	 * Returns the name of this s m a email history.
	 *
	 * @return the name of this s m a email history
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this s m a email history.
	 *
	 * @param name the name of this s m a email history
	 */
	public void setName(String name);

	/**
	 * Returns the history type of this s m a email history.
	 *
	 * @return the history type of this s m a email history
	 */
	public int getHistoryType();

	/**
	 * Sets the history type of this s m a email history.
	 *
	 * @param historyType the history type of this s m a email history
	 */
	public void setHistoryType(int historyType);

	/**
	 * Returns the email from of this s m a email history.
	 *
	 * @return the email from of this s m a email history
	 */
	@AutoEscape
	public String getEmailFrom();

	/**
	 * Sets the email from of this s m a email history.
	 *
	 * @param emailFrom the email from of this s m a email history
	 */
	public void setEmailFrom(String emailFrom);

	/**
	 * Returns the email to of this s m a email history.
	 *
	 * @return the email to of this s m a email history
	 */
	@AutoEscape
	public String getEmailTo();

	/**
	 * Sets the email to of this s m a email history.
	 *
	 * @param emailTo the email to of this s m a email history
	 */
	public void setEmailTo(String emailTo);

	/**
	 * Returns the email title of this s m a email history.
	 *
	 * @return the email title of this s m a email history
	 */
	@AutoEscape
	public String getEmailTitle();

	/**
	 * Sets the email title of this s m a email history.
	 *
	 * @param emailTitle the email title of this s m a email history
	 */
	public void setEmailTitle(String emailTitle);

	/**
	 * Returns the email content of this s m a email history.
	 *
	 * @return the email content of this s m a email history
	 */
	@AutoEscape
	public String getEmailContent();

	/**
	 * Sets the email content of this s m a email history.
	 *
	 * @param emailContent the email content of this s m a email history
	 */
	public void setEmailContent(String emailContent);

	/**
	 * Returns the is active of this s m a email history.
	 *
	 * @return the is active of this s m a email history
	 */
	public int getIsActive();

	/**
	 * Sets the is active of this s m a email history.
	 *
	 * @param isActive the is active of this s m a email history
	 */
	public void setIsActive(int isActive);

	/**
	 * Returns the created on of this s m a email history.
	 *
	 * @return the created on of this s m a email history
	 */
	public Date getCreatedOn();

	/**
	 * Sets the created on of this s m a email history.
	 *
	 * @param createdOn the created on of this s m a email history
	 */
	public void setCreatedOn(Date createdOn);

	/**
	 * Returns the created by of this s m a email history.
	 *
	 * @return the created by of this s m a email history
	 */
	@AutoEscape
	public String getCreatedBy();

	/**
	 * Sets the created by of this s m a email history.
	 *
	 * @param createdBy the created by of this s m a email history
	 */
	public void setCreatedBy(String createdBy);

	/**
	 * Returns the updated on of this s m a email history.
	 *
	 * @return the updated on of this s m a email history
	 */
	public Date getUpdatedOn();

	/**
	 * Sets the updated on of this s m a email history.
	 *
	 * @param updatedOn the updated on of this s m a email history
	 */
	public void setUpdatedOn(Date updatedOn);

	/**
	 * Returns the updated by of this s m a email history.
	 *
	 * @return the updated by of this s m a email history
	 */
	@AutoEscape
	public String getUpdatedBy();

	/**
	 * Sets the updated by of this s m a email history.
	 *
	 * @param updatedBy the updated by of this s m a email history
	 */
	public void setUpdatedBy(String updatedBy);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(SMAEmailHistory smaEmailHistory);

	public int hashCode();

	public CacheModel<SMAEmailHistory> toCacheModel();

	public SMAEmailHistory toEscapedModel();

	public String toString();

	public String toXmlString();
}