/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.pacnet.connect.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the SMARadcheck service. Represents a row in the &quot;PA_SMA_radcheck&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.pacnet.connect.model.impl.SMARadcheckModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.pacnet.connect.model.impl.SMARadcheckImpl}.
 * </p>
 *
 * @author CloudSmartz
 * @see SMARadcheck
 * @see com.pacnet.connect.model.impl.SMARadcheckImpl
 * @see com.pacnet.connect.model.impl.SMARadcheckModelImpl
 * @generated
 */
public interface SMARadcheckModel extends BaseModel<SMARadcheck> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a s m a radcheck model instance should use the {@link SMARadcheck} interface instead.
	 */

	/**
	 * Returns the primary key of this s m a radcheck.
	 *
	 * @return the primary key of this s m a radcheck
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this s m a radcheck.
	 *
	 * @param primaryKey the primary key of this s m a radcheck
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this s m a radcheck.
	 *
	 * @return the ID of this s m a radcheck
	 */
	public long getId();

	/**
	 * Sets the ID of this s m a radcheck.
	 *
	 * @param id the ID of this s m a radcheck
	 */
	public void setId(long id);

	/**
	 * Returns the company ID of this s m a radcheck.
	 *
	 * @return the company ID of this s m a radcheck
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this s m a radcheck.
	 *
	 * @param companyId the company ID of this s m a radcheck
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the username of this s m a radcheck.
	 *
	 * @return the username of this s m a radcheck
	 */
	@AutoEscape
	public String getUsername();

	/**
	 * Sets the username of this s m a radcheck.
	 *
	 * @param username the username of this s m a radcheck
	 */
	public void setUsername(String username);

	/**
	 * Returns the attribute of this s m a radcheck.
	 *
	 * @return the attribute of this s m a radcheck
	 */
	@AutoEscape
	public String getAttribute();

	/**
	 * Sets the attribute of this s m a radcheck.
	 *
	 * @param attribute the attribute of this s m a radcheck
	 */
	public void setAttribute(String attribute);

	/**
	 * Returns the op of this s m a radcheck.
	 *
	 * @return the op of this s m a radcheck
	 */
	@AutoEscape
	public String getOp();

	/**
	 * Sets the op of this s m a radcheck.
	 *
	 * @param op the op of this s m a radcheck
	 */
	public void setOp(String op);

	/**
	 * Returns the value of this s m a radcheck.
	 *
	 * @return the value of this s m a radcheck
	 */
	@AutoEscape
	public String getValue();

	/**
	 * Sets the value of this s m a radcheck.
	 *
	 * @param value the value of this s m a radcheck
	 */
	public void setValue(String value);

	/**
	 * Returns the is admin of this s m a radcheck.
	 *
	 * @return the is admin of this s m a radcheck
	 */
	public int getIsAdmin();

	/**
	 * Sets the is admin of this s m a radcheck.
	 *
	 * @param isAdmin the is admin of this s m a radcheck
	 */
	public void setIsAdmin(int isAdmin);

	/**
	 * Returns the is active of this s m a radcheck.
	 *
	 * @return the is active of this s m a radcheck
	 */
	public int getIsActive();

	/**
	 * Sets the is active of this s m a radcheck.
	 *
	 * @param isActive the is active of this s m a radcheck
	 */
	public void setIsActive(int isActive);

	/**
	 * Returns the created on of this s m a radcheck.
	 *
	 * @return the created on of this s m a radcheck
	 */
	public Date getCreatedOn();

	/**
	 * Sets the created on of this s m a radcheck.
	 *
	 * @param createdOn the created on of this s m a radcheck
	 */
	public void setCreatedOn(Date createdOn);

	/**
	 * Returns the created by of this s m a radcheck.
	 *
	 * @return the created by of this s m a radcheck
	 */
	@AutoEscape
	public String getCreatedBy();

	/**
	 * Sets the created by of this s m a radcheck.
	 *
	 * @param createdBy the created by of this s m a radcheck
	 */
	public void setCreatedBy(String createdBy);

	/**
	 * Returns the updated on of this s m a radcheck.
	 *
	 * @return the updated on of this s m a radcheck
	 */
	public Date getUpdatedOn();

	/**
	 * Sets the updated on of this s m a radcheck.
	 *
	 * @param updatedOn the updated on of this s m a radcheck
	 */
	public void setUpdatedOn(Date updatedOn);

	/**
	 * Returns the updated by of this s m a radcheck.
	 *
	 * @return the updated by of this s m a radcheck
	 */
	@AutoEscape
	public String getUpdatedBy();

	/**
	 * Sets the updated by of this s m a radcheck.
	 *
	 * @param updatedBy the updated by of this s m a radcheck
	 */
	public void setUpdatedBy(String updatedBy);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(SMARadcheck smaRadcheck);

	public int hashCode();

	public CacheModel<SMARadcheck> toCacheModel();

	public SMARadcheck toEscapedModel();

	public String toString();

	public String toXmlString();
}