/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.pacnet.connect.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the SMARadacct service. Represents a row in the &quot;PA_SMA_radacct&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.pacnet.connect.model.impl.SMARadacctModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.pacnet.connect.model.impl.SMARadacctImpl}.
 * </p>
 *
 * @author CloudSmartz
 * @see SMARadacct
 * @see com.pacnet.connect.model.impl.SMARadacctImpl
 * @see com.pacnet.connect.model.impl.SMARadacctModelImpl
 * @generated
 */
public interface SMARadacctModel extends BaseModel<SMARadacct> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a s m a radacct model instance should use the {@link SMARadacct} interface instead.
	 */

	/**
	 * Returns the primary key of this s m a radacct.
	 *
	 * @return the primary key of this s m a radacct
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this s m a radacct.
	 *
	 * @param primaryKey the primary key of this s m a radacct
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the rad acct ID of this s m a radacct.
	 *
	 * @return the rad acct ID of this s m a radacct
	 */
	public long getRadAcctId();

	/**
	 * Sets the rad acct ID of this s m a radacct.
	 *
	 * @param radAcctId the rad acct ID of this s m a radacct
	 */
	public void setRadAcctId(long radAcctId);

	/**
	 * Returns the radcheck ID of this s m a radacct.
	 *
	 * @return the radcheck ID of this s m a radacct
	 */
	public long getRadcheckId();

	/**
	 * Sets the radcheck ID of this s m a radacct.
	 *
	 * @param radcheckId the radcheck ID of this s m a radacct
	 */
	public void setRadcheckId(long radcheckId);

	/**
	 * Returns the acct session ID of this s m a radacct.
	 *
	 * @return the acct session ID of this s m a radacct
	 */
	@AutoEscape
	public String getAcctSessionId();

	/**
	 * Sets the acct session ID of this s m a radacct.
	 *
	 * @param acctSessionId the acct session ID of this s m a radacct
	 */
	public void setAcctSessionId(String acctSessionId);

	/**
	 * Returns the realm of this s m a radacct.
	 *
	 * @return the realm of this s m a radacct
	 */
	@AutoEscape
	public String getRealm();

	/**
	 * Sets the realm of this s m a radacct.
	 *
	 * @param realm the realm of this s m a radacct
	 */
	public void setRealm(String realm);

	/**
	 * Returns the acct start time of this s m a radacct.
	 *
	 * @return the acct start time of this s m a radacct
	 */
	public Date getAcctStartTime();

	/**
	 * Sets the acct start time of this s m a radacct.
	 *
	 * @param acctStartTime the acct start time of this s m a radacct
	 */
	public void setAcctStartTime(Date acctStartTime);

	/**
	 * Returns the acct stop time of this s m a radacct.
	 *
	 * @return the acct stop time of this s m a radacct
	 */
	public Date getAcctStopTime();

	/**
	 * Sets the acct stop time of this s m a radacct.
	 *
	 * @param acctStopTime the acct stop time of this s m a radacct
	 */
	public void setAcctStopTime(Date acctStopTime);

	/**
	 * Returns the acct session time of this s m a radacct.
	 *
	 * @return the acct session time of this s m a radacct
	 */
	public long getAcctSessionTime();

	/**
	 * Sets the acct session time of this s m a radacct.
	 *
	 * @param acctSessionTime the acct session time of this s m a radacct
	 */
	public void setAcctSessionTime(long acctSessionTime);

	/**
	 * Returns the acctterminate cause of this s m a radacct.
	 *
	 * @return the acctterminate cause of this s m a radacct
	 */
	@AutoEscape
	public String getAcctterminateCause();

	/**
	 * Sets the acctterminate cause of this s m a radacct.
	 *
	 * @param acctterminateCause the acctterminate cause of this s m a radacct
	 */
	public void setAcctterminateCause(String acctterminateCause);

	/**
	 * Returns the is active of this s m a radacct.
	 *
	 * @return the is active of this s m a radacct
	 */
	public int getIsActive();

	/**
	 * Sets the is active of this s m a radacct.
	 *
	 * @param isActive the is active of this s m a radacct
	 */
	public void setIsActive(int isActive);

	/**
	 * Returns the created on of this s m a radacct.
	 *
	 * @return the created on of this s m a radacct
	 */
	public Date getCreatedOn();

	/**
	 * Sets the created on of this s m a radacct.
	 *
	 * @param createdOn the created on of this s m a radacct
	 */
	public void setCreatedOn(Date createdOn);

	/**
	 * Returns the created by of this s m a radacct.
	 *
	 * @return the created by of this s m a radacct
	 */
	@AutoEscape
	public String getCreatedBy();

	/**
	 * Sets the created by of this s m a radacct.
	 *
	 * @param createdBy the created by of this s m a radacct
	 */
	public void setCreatedBy(String createdBy);

	/**
	 * Returns the updated on of this s m a radacct.
	 *
	 * @return the updated on of this s m a radacct
	 */
	public Date getUpdatedOn();

	/**
	 * Sets the updated on of this s m a radacct.
	 *
	 * @param updatedOn the updated on of this s m a radacct
	 */
	public void setUpdatedOn(Date updatedOn);

	/**
	 * Returns the updated by of this s m a radacct.
	 *
	 * @return the updated by of this s m a radacct
	 */
	@AutoEscape
	public String getUpdatedBy();

	/**
	 * Sets the updated by of this s m a radacct.
	 *
	 * @param updatedBy the updated by of this s m a radacct
	 */
	public void setUpdatedBy(String updatedBy);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(SMARadacct smaRadacct);

	public int hashCode();

	public CacheModel<SMARadacct> toCacheModel();

	public SMARadacct toEscapedModel();

	public String toString();

	public String toXmlString();
}