/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.pacnet.connect.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the SMAReservation service. Represents a row in the &quot;PA_SMA_reservation&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.pacnet.connect.model.impl.SMAReservationModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.pacnet.connect.model.impl.SMAReservationImpl}.
 * </p>
 *
 * @author CloudSmartz
 * @see SMAReservation
 * @see com.pacnet.connect.model.impl.SMAReservationImpl
 * @see com.pacnet.connect.model.impl.SMAReservationModelImpl
 * @generated
 */
public interface SMAReservationModel extends BaseModel<SMAReservation> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a s m a reservation model instance should use the {@link SMAReservation} interface instead.
	 */

	/**
	 * Returns the primary key of this s m a reservation.
	 *
	 * @return the primary key of this s m a reservation
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this s m a reservation.
	 *
	 * @param primaryKey the primary key of this s m a reservation
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this s m a reservation.
	 *
	 * @return the ID of this s m a reservation
	 */
	public long getId();

	/**
	 * Sets the ID of this s m a reservation.
	 *
	 * @param id the ID of this s m a reservation
	 */
	public void setId(long id);

	/**
	 * Returns the name of this s m a reservation.
	 *
	 * @return the name of this s m a reservation
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this s m a reservation.
	 *
	 * @param name the name of this s m a reservation
	 */
	public void setName(String name);

	/**
	 * Returns the start date of this s m a reservation.
	 *
	 * @return the start date of this s m a reservation
	 */
	public Date getStartDate();

	/**
	 * Sets the start date of this s m a reservation.
	 *
	 * @param startDate the start date of this s m a reservation
	 */
	public void setStartDate(Date startDate);

	/**
	 * Returns the end date of this s m a reservation.
	 *
	 * @return the end date of this s m a reservation
	 */
	public Date getEndDate();

	/**
	 * Sets the end date of this s m a reservation.
	 *
	 * @param endDate the end date of this s m a reservation
	 */
	public void setEndDate(Date endDate);

	/**
	 * Returns the owner of this s m a reservation.
	 *
	 * @return the owner of this s m a reservation
	 */
	@AutoEscape
	public String getOwner();

	/**
	 * Sets the owner of this s m a reservation.
	 *
	 * @param owner the owner of this s m a reservation
	 */
	public void setOwner(String owner);

	/**
	 * Returns the provision of this s m a reservation.
	 *
	 * @return the provision of this s m a reservation
	 */
	public int getProvision();

	/**
	 * Sets the provision of this s m a reservation.
	 *
	 * @param provision the provision of this s m a reservation
	 */
	public void setProvision(int provision);

	/**
	 * Returns the is active of this s m a reservation.
	 *
	 * @return the is active of this s m a reservation
	 */
	public int getIsActive();

	/**
	 * Sets the is active of this s m a reservation.
	 *
	 * @param isActive the is active of this s m a reservation
	 */
	public void setIsActive(int isActive);

	/**
	 * Returns the created on of this s m a reservation.
	 *
	 * @return the created on of this s m a reservation
	 */
	public Date getCreatedOn();

	/**
	 * Sets the created on of this s m a reservation.
	 *
	 * @param createdOn the created on of this s m a reservation
	 */
	public void setCreatedOn(Date createdOn);

	/**
	 * Returns the created by of this s m a reservation.
	 *
	 * @return the created by of this s m a reservation
	 */
	@AutoEscape
	public String getCreatedBy();

	/**
	 * Sets the created by of this s m a reservation.
	 *
	 * @param createdBy the created by of this s m a reservation
	 */
	public void setCreatedBy(String createdBy);

	/**
	 * Returns the updated on of this s m a reservation.
	 *
	 * @return the updated on of this s m a reservation
	 */
	public Date getUpdatedOn();

	/**
	 * Sets the updated on of this s m a reservation.
	 *
	 * @param updatedOn the updated on of this s m a reservation
	 */
	public void setUpdatedOn(Date updatedOn);

	/**
	 * Returns the updated by of this s m a reservation.
	 *
	 * @return the updated by of this s m a reservation
	 */
	@AutoEscape
	public String getUpdatedBy();

	/**
	 * Sets the updated by of this s m a reservation.
	 *
	 * @param updatedBy the updated by of this s m a reservation
	 */
	public void setUpdatedBy(String updatedBy);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(SMAReservation smaReservation);

	public int hashCode();

	public CacheModel<SMAReservation> toCacheModel();

	public SMAReservation toEscapedModel();

	public String toString();

	public String toXmlString();
}