/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.pacnet.connect.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import com.pacnet.connect.model.AccessRequestNoteHistory;
import com.pacnet.connect.model.AccessRequestNoteHistoryModel;
import com.pacnet.connect.model.AccessRequestNoteHistorySoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the AccessRequestNoteHistory service. Represents a row in the &quot;Access_Request_Note_History&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.pacnet.connect.model.AccessRequestNoteHistoryModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AccessRequestNoteHistoryImpl}.
 * </p>
 *
 * @author CloudSmartz
 * @see AccessRequestNoteHistoryImpl
 * @see com.pacnet.connect.model.AccessRequestNoteHistory
 * @see com.pacnet.connect.model.AccessRequestNoteHistoryModel
 * @generated
 */
@JSON(strict = true)
public class AccessRequestNoteHistoryModelImpl extends BaseModelImpl<AccessRequestNoteHistory>
	implements AccessRequestNoteHistoryModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a access request note history model instance should use the {@link com.pacnet.connect.model.AccessRequestNoteHistory} interface instead.
	 */
	public static final String TABLE_NAME = "Access_Request_Note_History";
	public static final Object[][] TABLE_COLUMNS = {
			{ "ID", Types.BIGINT },
			{ "Access_Request_ID", Types.BIGINT },
			{ "Customer_ID", Types.BIGINT },
			{ "Note", Types.VARCHAR },
			{ "Table_Name", Types.VARCHAR },
			{ "IsActive", Types.BOOLEAN },
			{ "Created_On", Types.TIMESTAMP },
			{ "Created_By", Types.VARCHAR },
			{ "Updated_On", Types.TIMESTAMP },
			{ "Updated_By", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table Access_Request_Note_History (ID LONG not null primary key IDENTITY,Access_Request_ID LONG,Customer_ID LONG,Note VARCHAR(75) null,Table_Name VARCHAR(75) null,IsActive BOOLEAN,Created_On DATE null,Created_By VARCHAR(75) null,Updated_On DATE null,Updated_By VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table Access_Request_Note_History";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.pacnet.connect.model.AccessRequestNoteHistory"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.pacnet.connect.model.AccessRequestNoteHistory"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.pacnet.connect.model.AccessRequestNoteHistory"),
			true);
	public static long ACCESSREQUESTID_COLUMN_BITMASK = 1L;
	public static long CUSTOMERID_COLUMN_BITMASK = 2L;
	public static long TABLENAME_COLUMN_BITMASK = 4L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static AccessRequestNoteHistory toModel(
		AccessRequestNoteHistorySoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		AccessRequestNoteHistory model = new AccessRequestNoteHistoryImpl();

		model.setId(soapModel.getId());
		model.setAccessRequestId(soapModel.getAccessRequestId());
		model.setCustomerId(soapModel.getCustomerId());
		model.setNote(soapModel.getNote());
		model.setTableName(soapModel.getTableName());
		model.setIsActive(soapModel.getIsActive());
		model.setCreatedOn(soapModel.getCreatedOn());
		model.setCreatedBy(soapModel.getCreatedBy());
		model.setUpdatedOn(soapModel.getUpdatedOn());
		model.setUpdatedBy(soapModel.getUpdatedBy());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<AccessRequestNoteHistory> toModels(
		AccessRequestNoteHistorySoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<AccessRequestNoteHistory> models = new ArrayList<AccessRequestNoteHistory>(soapModels.length);

		for (AccessRequestNoteHistorySoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.pacnet.connect.model.AccessRequestNoteHistory"));

	public AccessRequestNoteHistoryModelImpl() {
	}

	public long getPrimaryKey() {
		return _id;
	}

	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_id);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return AccessRequestNoteHistory.class;
	}

	public String getModelClassName() {
		return AccessRequestNoteHistory.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("id", getId());
		attributes.put("accessRequestId", getAccessRequestId());
		attributes.put("customerId", getCustomerId());
		attributes.put("note", getNote());
		attributes.put("tableName", getTableName());
		attributes.put("isActive", getIsActive());
		attributes.put("createdOn", getCreatedOn());
		attributes.put("createdBy", getCreatedBy());
		attributes.put("updatedOn", getUpdatedOn());
		attributes.put("updatedBy", getUpdatedBy());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long id = (Long)attributes.get("id");

		if (id != null) {
			setId(id);
		}

		Long accessRequestId = (Long)attributes.get("accessRequestId");

		if (accessRequestId != null) {
			setAccessRequestId(accessRequestId);
		}

		Long customerId = (Long)attributes.get("customerId");

		if (customerId != null) {
			setCustomerId(customerId);
		}

		String note = (String)attributes.get("note");

		if (note != null) {
			setNote(note);
		}

		String tableName = (String)attributes.get("tableName");

		if (tableName != null) {
			setTableName(tableName);
		}

		Boolean isActive = (Boolean)attributes.get("isActive");

		if (isActive != null) {
			setIsActive(isActive);
		}

		Date createdOn = (Date)attributes.get("createdOn");

		if (createdOn != null) {
			setCreatedOn(createdOn);
		}

		String createdBy = (String)attributes.get("createdBy");

		if (createdBy != null) {
			setCreatedBy(createdBy);
		}

		Date updatedOn = (Date)attributes.get("updatedOn");

		if (updatedOn != null) {
			setUpdatedOn(updatedOn);
		}

		String updatedBy = (String)attributes.get("updatedBy");

		if (updatedBy != null) {
			setUpdatedBy(updatedBy);
		}
	}

	@JSON
	public long getId() {
		return _id;
	}

	public void setId(long id) {
		_id = id;
	}

	@JSON
	public long getAccessRequestId() {
		return _accessRequestId;
	}

	public void setAccessRequestId(long accessRequestId) {
		_columnBitmask |= ACCESSREQUESTID_COLUMN_BITMASK;

		if (!_setOriginalAccessRequestId) {
			_setOriginalAccessRequestId = true;

			_originalAccessRequestId = _accessRequestId;
		}

		_accessRequestId = accessRequestId;
	}

	public long getOriginalAccessRequestId() {
		return _originalAccessRequestId;
	}

	@JSON
	public long getCustomerId() {
		return _customerId;
	}

	public void setCustomerId(long customerId) {
		_columnBitmask |= CUSTOMERID_COLUMN_BITMASK;

		if (!_setOriginalCustomerId) {
			_setOriginalCustomerId = true;

			_originalCustomerId = _customerId;
		}

		_customerId = customerId;
	}

	public long getOriginalCustomerId() {
		return _originalCustomerId;
	}

	@JSON
	public String getNote() {
		if (_note == null) {
			return StringPool.BLANK;
		}
		else {
			return _note;
		}
	}

	public void setNote(String note) {
		_note = note;
	}

	@JSON
	public String getTableName() {
		if (_tableName == null) {
			return StringPool.BLANK;
		}
		else {
			return _tableName;
		}
	}

	public void setTableName(String tableName) {
		_columnBitmask |= TABLENAME_COLUMN_BITMASK;

		if (_originalTableName == null) {
			_originalTableName = _tableName;
		}

		_tableName = tableName;
	}

	public String getOriginalTableName() {
		return GetterUtil.getString(_originalTableName);
	}

	@JSON
	public boolean getIsActive() {
		return _isActive;
	}

	public boolean isIsActive() {
		return _isActive;
	}

	public void setIsActive(boolean isActive) {
		_isActive = isActive;
	}

	@JSON
	public Date getCreatedOn() {
		return _createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		_createdOn = createdOn;
	}

	@JSON
	public String getCreatedBy() {
		if (_createdBy == null) {
			return StringPool.BLANK;
		}
		else {
			return _createdBy;
		}
	}

	public void setCreatedBy(String createdBy) {
		_createdBy = createdBy;
	}

	@JSON
	public Date getUpdatedOn() {
		return _updatedOn;
	}

	public void setUpdatedOn(Date updatedOn) {
		_updatedOn = updatedOn;
	}

	@JSON
	public String getUpdatedBy() {
		if (_updatedBy == null) {
			return StringPool.BLANK;
		}
		else {
			return _updatedBy;
		}
	}

	public void setUpdatedBy(String updatedBy) {
		_updatedBy = updatedBy;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			AccessRequestNoteHistory.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public AccessRequestNoteHistory toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (AccessRequestNoteHistory)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public Object clone() {
		AccessRequestNoteHistoryImpl accessRequestNoteHistoryImpl = new AccessRequestNoteHistoryImpl();

		accessRequestNoteHistoryImpl.setId(getId());
		accessRequestNoteHistoryImpl.setAccessRequestId(getAccessRequestId());
		accessRequestNoteHistoryImpl.setCustomerId(getCustomerId());
		accessRequestNoteHistoryImpl.setNote(getNote());
		accessRequestNoteHistoryImpl.setTableName(getTableName());
		accessRequestNoteHistoryImpl.setIsActive(getIsActive());
		accessRequestNoteHistoryImpl.setCreatedOn(getCreatedOn());
		accessRequestNoteHistoryImpl.setCreatedBy(getCreatedBy());
		accessRequestNoteHistoryImpl.setUpdatedOn(getUpdatedOn());
		accessRequestNoteHistoryImpl.setUpdatedBy(getUpdatedBy());

		accessRequestNoteHistoryImpl.resetOriginalValues();

		return accessRequestNoteHistoryImpl;
	}

	public int compareTo(AccessRequestNoteHistory accessRequestNoteHistory) {
		long primaryKey = accessRequestNoteHistory.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		AccessRequestNoteHistory accessRequestNoteHistory = null;

		try {
			accessRequestNoteHistory = (AccessRequestNoteHistory)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long primaryKey = accessRequestNoteHistory.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		AccessRequestNoteHistoryModelImpl accessRequestNoteHistoryModelImpl = this;

		accessRequestNoteHistoryModelImpl._originalAccessRequestId = accessRequestNoteHistoryModelImpl._accessRequestId;

		accessRequestNoteHistoryModelImpl._setOriginalAccessRequestId = false;

		accessRequestNoteHistoryModelImpl._originalCustomerId = accessRequestNoteHistoryModelImpl._customerId;

		accessRequestNoteHistoryModelImpl._setOriginalCustomerId = false;

		accessRequestNoteHistoryModelImpl._originalTableName = accessRequestNoteHistoryModelImpl._tableName;

		accessRequestNoteHistoryModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<AccessRequestNoteHistory> toCacheModel() {
		AccessRequestNoteHistoryCacheModel accessRequestNoteHistoryCacheModel = new AccessRequestNoteHistoryCacheModel();

		accessRequestNoteHistoryCacheModel.id = getId();

		accessRequestNoteHistoryCacheModel.accessRequestId = getAccessRequestId();

		accessRequestNoteHistoryCacheModel.customerId = getCustomerId();

		accessRequestNoteHistoryCacheModel.note = getNote();

		String note = accessRequestNoteHistoryCacheModel.note;

		if ((note != null) && (note.length() == 0)) {
			accessRequestNoteHistoryCacheModel.note = null;
		}

		accessRequestNoteHistoryCacheModel.tableName = getTableName();

		String tableName = accessRequestNoteHistoryCacheModel.tableName;

		if ((tableName != null) && (tableName.length() == 0)) {
			accessRequestNoteHistoryCacheModel.tableName = null;
		}

		accessRequestNoteHistoryCacheModel.isActive = getIsActive();

		Date createdOn = getCreatedOn();

		if (createdOn != null) {
			accessRequestNoteHistoryCacheModel.createdOn = createdOn.getTime();
		}
		else {
			accessRequestNoteHistoryCacheModel.createdOn = Long.MIN_VALUE;
		}

		accessRequestNoteHistoryCacheModel.createdBy = getCreatedBy();

		String createdBy = accessRequestNoteHistoryCacheModel.createdBy;

		if ((createdBy != null) && (createdBy.length() == 0)) {
			accessRequestNoteHistoryCacheModel.createdBy = null;
		}

		Date updatedOn = getUpdatedOn();

		if (updatedOn != null) {
			accessRequestNoteHistoryCacheModel.updatedOn = updatedOn.getTime();
		}
		else {
			accessRequestNoteHistoryCacheModel.updatedOn = Long.MIN_VALUE;
		}

		accessRequestNoteHistoryCacheModel.updatedBy = getUpdatedBy();

		String updatedBy = accessRequestNoteHistoryCacheModel.updatedBy;

		if ((updatedBy != null) && (updatedBy.length() == 0)) {
			accessRequestNoteHistoryCacheModel.updatedBy = null;
		}

		return accessRequestNoteHistoryCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(21);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", accessRequestId=");
		sb.append(getAccessRequestId());
		sb.append(", customerId=");
		sb.append(getCustomerId());
		sb.append(", note=");
		sb.append(getNote());
		sb.append(", tableName=");
		sb.append(getTableName());
		sb.append(", isActive=");
		sb.append(getIsActive());
		sb.append(", createdOn=");
		sb.append(getCreatedOn());
		sb.append(", createdBy=");
		sb.append(getCreatedBy());
		sb.append(", updatedOn=");
		sb.append(getUpdatedOn());
		sb.append(", updatedBy=");
		sb.append(getUpdatedBy());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(34);

		sb.append("<model><model-name>");
		sb.append("com.pacnet.connect.model.AccessRequestNoteHistory");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>accessRequestId</column-name><column-value><![CDATA[");
		sb.append(getAccessRequestId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>customerId</column-name><column-value><![CDATA[");
		sb.append(getCustomerId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>note</column-name><column-value><![CDATA[");
		sb.append(getNote());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tableName</column-name><column-value><![CDATA[");
		sb.append(getTableName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>isActive</column-name><column-value><![CDATA[");
		sb.append(getIsActive());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createdOn</column-name><column-value><![CDATA[");
		sb.append(getCreatedOn());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createdBy</column-name><column-value><![CDATA[");
		sb.append(getCreatedBy());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>updatedOn</column-name><column-value><![CDATA[");
		sb.append(getUpdatedOn());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>updatedBy</column-name><column-value><![CDATA[");
		sb.append(getUpdatedBy());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = AccessRequestNoteHistory.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			AccessRequestNoteHistory.class
		};
	private long _id;
	private long _accessRequestId;
	private long _originalAccessRequestId;
	private boolean _setOriginalAccessRequestId;
	private long _customerId;
	private long _originalCustomerId;
	private boolean _setOriginalCustomerId;
	private String _note;
	private String _tableName;
	private String _originalTableName;
	private boolean _isActive;
	private Date _createdOn;
	private String _createdBy;
	private Date _updatedOn;
	private String _updatedBy;
	private long _columnBitmask;
	private AccessRequestNoteHistory _escapedModelProxy;
}