/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.pacnet.connect.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import com.pacnet.connect.model.FacilityUserMapping;
import com.pacnet.connect.model.FacilityUserMappingModel;
import com.pacnet.connect.model.FacilityUserMappingSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the FacilityUserMapping service. Represents a row in the &quot;Facility_User_Mapping&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.pacnet.connect.model.FacilityUserMappingModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link FacilityUserMappingImpl}.
 * </p>
 *
 * @author CloudSmartz
 * @see FacilityUserMappingImpl
 * @see com.pacnet.connect.model.FacilityUserMapping
 * @see com.pacnet.connect.model.FacilityUserMappingModel
 * @generated
 */
@JSON(strict = true)
public class FacilityUserMappingModelImpl extends BaseModelImpl<FacilityUserMapping>
	implements FacilityUserMappingModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a facility user mapping model instance should use the {@link com.pacnet.connect.model.FacilityUserMapping} interface instead.
	 */
	public static final String TABLE_NAME = "Facility_User_Mapping";
	public static final Object[][] TABLE_COLUMNS = {
			{ "ID", Types.BIGINT },
			{ "Customer_ID", Types.BIGINT },
			{ "Facility_ID", Types.BIGINT },
			{ "Customer_Contact_ID", Types.BIGINT },
			{ "IsActive", Types.BOOLEAN },
			{ "non_pacnet_user_ID", Types.BIGINT },
			{ "Created_On", Types.TIMESTAMP },
			{ "Created_By", Types.VARCHAR },
			{ "Updated_On", Types.TIMESTAMP },
			{ "Updated_By", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table Facility_User_Mapping (ID LONG not null primary key IDENTITY,Customer_ID LONG,Facility_ID LONG,Customer_Contact_ID LONG,IsActive BOOLEAN,non_pacnet_user_ID LONG,Created_On DATE null,Created_By VARCHAR(75) null,Updated_On DATE null,Updated_By VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table Facility_User_Mapping";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.pacnet.connect.model.FacilityUserMapping"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.pacnet.connect.model.FacilityUserMapping"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.pacnet.connect.model.FacilityUserMapping"),
			true);
	public static long CUSTOMERCONTACTID_COLUMN_BITMASK = 1L;
	public static long CUSTOMERID_COLUMN_BITMASK = 2L;
	public static long FACILTYID_COLUMN_BITMASK = 4L;
	public static long NONPACNETUSERID_COLUMN_BITMASK = 8L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static FacilityUserMapping toModel(FacilityUserMappingSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		FacilityUserMapping model = new FacilityUserMappingImpl();

		model.setId(soapModel.getId());
		model.setCustomerId(soapModel.getCustomerId());
		model.setFaciltyId(soapModel.getFaciltyId());
		model.setCustomerContactId(soapModel.getCustomerContactId());
		model.setIsActive(soapModel.getIsActive());
		model.setNonPacnetUserId(soapModel.getNonPacnetUserId());
		model.setCreatedOn(soapModel.getCreatedOn());
		model.setCreatedBy(soapModel.getCreatedBy());
		model.setUpdatedOn(soapModel.getUpdatedOn());
		model.setUpdatedBy(soapModel.getUpdatedBy());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<FacilityUserMapping> toModels(
		FacilityUserMappingSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<FacilityUserMapping> models = new ArrayList<FacilityUserMapping>(soapModels.length);

		for (FacilityUserMappingSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.pacnet.connect.model.FacilityUserMapping"));

	public FacilityUserMappingModelImpl() {
	}

	public long getPrimaryKey() {
		return _id;
	}

	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_id);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return FacilityUserMapping.class;
	}

	public String getModelClassName() {
		return FacilityUserMapping.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("id", getId());
		attributes.put("customerId", getCustomerId());
		attributes.put("faciltyId", getFaciltyId());
		attributes.put("customerContactId", getCustomerContactId());
		attributes.put("isActive", getIsActive());
		attributes.put("nonPacnetUserId", getNonPacnetUserId());
		attributes.put("createdOn", getCreatedOn());
		attributes.put("createdBy", getCreatedBy());
		attributes.put("updatedOn", getUpdatedOn());
		attributes.put("updatedBy", getUpdatedBy());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long id = (Long)attributes.get("id");

		if (id != null) {
			setId(id);
		}

		Long customerId = (Long)attributes.get("customerId");

		if (customerId != null) {
			setCustomerId(customerId);
		}

		Long faciltyId = (Long)attributes.get("faciltyId");

		if (faciltyId != null) {
			setFaciltyId(faciltyId);
		}

		Long customerContactId = (Long)attributes.get("customerContactId");

		if (customerContactId != null) {
			setCustomerContactId(customerContactId);
		}

		Boolean isActive = (Boolean)attributes.get("isActive");

		if (isActive != null) {
			setIsActive(isActive);
		}

		Long nonPacnetUserId = (Long)attributes.get("nonPacnetUserId");

		if (nonPacnetUserId != null) {
			setNonPacnetUserId(nonPacnetUserId);
		}

		Date createdOn = (Date)attributes.get("createdOn");

		if (createdOn != null) {
			setCreatedOn(createdOn);
		}

		String createdBy = (String)attributes.get("createdBy");

		if (createdBy != null) {
			setCreatedBy(createdBy);
		}

		Date updatedOn = (Date)attributes.get("updatedOn");

		if (updatedOn != null) {
			setUpdatedOn(updatedOn);
		}

		String updatedBy = (String)attributes.get("updatedBy");

		if (updatedBy != null) {
			setUpdatedBy(updatedBy);
		}
	}

	@JSON
	public long getId() {
		return _id;
	}

	public void setId(long id) {
		_id = id;
	}

	@JSON
	public long getCustomerId() {
		return _customerId;
	}

	public void setCustomerId(long customerId) {
		_columnBitmask |= CUSTOMERID_COLUMN_BITMASK;

		if (!_setOriginalCustomerId) {
			_setOriginalCustomerId = true;

			_originalCustomerId = _customerId;
		}

		_customerId = customerId;
	}

	public long getOriginalCustomerId() {
		return _originalCustomerId;
	}

	@JSON
	public long getFaciltyId() {
		return _faciltyId;
	}

	public void setFaciltyId(long faciltyId) {
		_columnBitmask |= FACILTYID_COLUMN_BITMASK;

		if (!_setOriginalFaciltyId) {
			_setOriginalFaciltyId = true;

			_originalFaciltyId = _faciltyId;
		}

		_faciltyId = faciltyId;
	}

	public long getOriginalFaciltyId() {
		return _originalFaciltyId;
	}

	@JSON
	public long getCustomerContactId() {
		return _customerContactId;
	}

	public void setCustomerContactId(long customerContactId) {
		_columnBitmask |= CUSTOMERCONTACTID_COLUMN_BITMASK;

		if (!_setOriginalCustomerContactId) {
			_setOriginalCustomerContactId = true;

			_originalCustomerContactId = _customerContactId;
		}

		_customerContactId = customerContactId;
	}

	public long getOriginalCustomerContactId() {
		return _originalCustomerContactId;
	}

	@JSON
	public boolean getIsActive() {
		return _isActive;
	}

	public boolean isIsActive() {
		return _isActive;
	}

	public void setIsActive(boolean isActive) {
		_isActive = isActive;
	}

	@JSON
	public long getNonPacnetUserId() {
		return _nonPacnetUserId;
	}

	public void setNonPacnetUserId(long nonPacnetUserId) {
		_columnBitmask |= NONPACNETUSERID_COLUMN_BITMASK;

		if (!_setOriginalNonPacnetUserId) {
			_setOriginalNonPacnetUserId = true;

			_originalNonPacnetUserId = _nonPacnetUserId;
		}

		_nonPacnetUserId = nonPacnetUserId;
	}

	public String getNonPacnetUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getNonPacnetUserId(), "uuid",
			_nonPacnetUserUuid);
	}

	public void setNonPacnetUserUuid(String nonPacnetUserUuid) {
		_nonPacnetUserUuid = nonPacnetUserUuid;
	}

	public long getOriginalNonPacnetUserId() {
		return _originalNonPacnetUserId;
	}

	@JSON
	public Date getCreatedOn() {
		return _createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		_createdOn = createdOn;
	}

	@JSON
	public String getCreatedBy() {
		if (_createdBy == null) {
			return StringPool.BLANK;
		}
		else {
			return _createdBy;
		}
	}

	public void setCreatedBy(String createdBy) {
		_createdBy = createdBy;
	}

	@JSON
	public Date getUpdatedOn() {
		return _updatedOn;
	}

	public void setUpdatedOn(Date updatedOn) {
		_updatedOn = updatedOn;
	}

	@JSON
	public String getUpdatedBy() {
		if (_updatedBy == null) {
			return StringPool.BLANK;
		}
		else {
			return _updatedBy;
		}
	}

	public void setUpdatedBy(String updatedBy) {
		_updatedBy = updatedBy;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			FacilityUserMapping.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public FacilityUserMapping toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (FacilityUserMapping)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public Object clone() {
		FacilityUserMappingImpl facilityUserMappingImpl = new FacilityUserMappingImpl();

		facilityUserMappingImpl.setId(getId());
		facilityUserMappingImpl.setCustomerId(getCustomerId());
		facilityUserMappingImpl.setFaciltyId(getFaciltyId());
		facilityUserMappingImpl.setCustomerContactId(getCustomerContactId());
		facilityUserMappingImpl.setIsActive(getIsActive());
		facilityUserMappingImpl.setNonPacnetUserId(getNonPacnetUserId());
		facilityUserMappingImpl.setCreatedOn(getCreatedOn());
		facilityUserMappingImpl.setCreatedBy(getCreatedBy());
		facilityUserMappingImpl.setUpdatedOn(getUpdatedOn());
		facilityUserMappingImpl.setUpdatedBy(getUpdatedBy());

		facilityUserMappingImpl.resetOriginalValues();

		return facilityUserMappingImpl;
	}

	public int compareTo(FacilityUserMapping facilityUserMapping) {
		long primaryKey = facilityUserMapping.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		FacilityUserMapping facilityUserMapping = null;

		try {
			facilityUserMapping = (FacilityUserMapping)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long primaryKey = facilityUserMapping.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		FacilityUserMappingModelImpl facilityUserMappingModelImpl = this;

		facilityUserMappingModelImpl._originalCustomerId = facilityUserMappingModelImpl._customerId;

		facilityUserMappingModelImpl._setOriginalCustomerId = false;

		facilityUserMappingModelImpl._originalFaciltyId = facilityUserMappingModelImpl._faciltyId;

		facilityUserMappingModelImpl._setOriginalFaciltyId = false;

		facilityUserMappingModelImpl._originalCustomerContactId = facilityUserMappingModelImpl._customerContactId;

		facilityUserMappingModelImpl._setOriginalCustomerContactId = false;

		facilityUserMappingModelImpl._originalNonPacnetUserId = facilityUserMappingModelImpl._nonPacnetUserId;

		facilityUserMappingModelImpl._setOriginalNonPacnetUserId = false;

		facilityUserMappingModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<FacilityUserMapping> toCacheModel() {
		FacilityUserMappingCacheModel facilityUserMappingCacheModel = new FacilityUserMappingCacheModel();

		facilityUserMappingCacheModel.id = getId();

		facilityUserMappingCacheModel.customerId = getCustomerId();

		facilityUserMappingCacheModel.faciltyId = getFaciltyId();

		facilityUserMappingCacheModel.customerContactId = getCustomerContactId();

		facilityUserMappingCacheModel.isActive = getIsActive();

		facilityUserMappingCacheModel.nonPacnetUserId = getNonPacnetUserId();

		Date createdOn = getCreatedOn();

		if (createdOn != null) {
			facilityUserMappingCacheModel.createdOn = createdOn.getTime();
		}
		else {
			facilityUserMappingCacheModel.createdOn = Long.MIN_VALUE;
		}

		facilityUserMappingCacheModel.createdBy = getCreatedBy();

		String createdBy = facilityUserMappingCacheModel.createdBy;

		if ((createdBy != null) && (createdBy.length() == 0)) {
			facilityUserMappingCacheModel.createdBy = null;
		}

		Date updatedOn = getUpdatedOn();

		if (updatedOn != null) {
			facilityUserMappingCacheModel.updatedOn = updatedOn.getTime();
		}
		else {
			facilityUserMappingCacheModel.updatedOn = Long.MIN_VALUE;
		}

		facilityUserMappingCacheModel.updatedBy = getUpdatedBy();

		String updatedBy = facilityUserMappingCacheModel.updatedBy;

		if ((updatedBy != null) && (updatedBy.length() == 0)) {
			facilityUserMappingCacheModel.updatedBy = null;
		}

		return facilityUserMappingCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(21);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", customerId=");
		sb.append(getCustomerId());
		sb.append(", faciltyId=");
		sb.append(getFaciltyId());
		sb.append(", customerContactId=");
		sb.append(getCustomerContactId());
		sb.append(", isActive=");
		sb.append(getIsActive());
		sb.append(", nonPacnetUserId=");
		sb.append(getNonPacnetUserId());
		sb.append(", createdOn=");
		sb.append(getCreatedOn());
		sb.append(", createdBy=");
		sb.append(getCreatedBy());
		sb.append(", updatedOn=");
		sb.append(getUpdatedOn());
		sb.append(", updatedBy=");
		sb.append(getUpdatedBy());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(34);

		sb.append("<model><model-name>");
		sb.append("com.pacnet.connect.model.FacilityUserMapping");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>customerId</column-name><column-value><![CDATA[");
		sb.append(getCustomerId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>faciltyId</column-name><column-value><![CDATA[");
		sb.append(getFaciltyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>customerContactId</column-name><column-value><![CDATA[");
		sb.append(getCustomerContactId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>isActive</column-name><column-value><![CDATA[");
		sb.append(getIsActive());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nonPacnetUserId</column-name><column-value><![CDATA[");
		sb.append(getNonPacnetUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createdOn</column-name><column-value><![CDATA[");
		sb.append(getCreatedOn());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createdBy</column-name><column-value><![CDATA[");
		sb.append(getCreatedBy());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>updatedOn</column-name><column-value><![CDATA[");
		sb.append(getUpdatedOn());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>updatedBy</column-name><column-value><![CDATA[");
		sb.append(getUpdatedBy());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = FacilityUserMapping.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			FacilityUserMapping.class
		};
	private long _id;
	private long _customerId;
	private long _originalCustomerId;
	private boolean _setOriginalCustomerId;
	private long _faciltyId;
	private long _originalFaciltyId;
	private boolean _setOriginalFaciltyId;
	private long _customerContactId;
	private long _originalCustomerContactId;
	private boolean _setOriginalCustomerContactId;
	private boolean _isActive;
	private long _nonPacnetUserId;
	private String _nonPacnetUserUuid;
	private long _originalNonPacnetUserId;
	private boolean _setOriginalNonPacnetUserId;
	private Date _createdOn;
	private String _createdBy;
	private Date _updatedOn;
	private String _updatedBy;
	private long _columnBitmask;
	private FacilityUserMapping _escapedModelProxy;
}