/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.pacnet.connect.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.pacnet.connect.model.FacilityUserService;
import com.pacnet.connect.service.FacilityUserServiceLocalServiceUtil;

/**
 * The extended model base implementation for the FacilityUserService service. Represents a row in the &quot;Facility_User_Service_Mapping&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link FacilityUserServiceImpl}.
 * </p>
 *
 * @author CloudSmartz
 * @see FacilityUserServiceImpl
 * @see com.pacnet.connect.model.FacilityUserService
 * @generated
 */
public abstract class FacilityUserServiceBaseImpl
	extends FacilityUserServiceModelImpl implements FacilityUserService {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a facility user service model instance should use the {@link FacilityUserService} interface instead.
	 */
	public void persist() throws SystemException {
		if (this.isNew()) {
			FacilityUserServiceLocalServiceUtil.addFacilityUserService(this);
		}
		else {
			FacilityUserServiceLocalServiceUtil.updateFacilityUserService(this);
		}
	}
}