/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.pacnet.connect.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.pacnet.connect.model.FacilityExternalVisitor;
import com.pacnet.connect.service.FacilityExternalVisitorLocalServiceUtil;

/**
 * The extended model base implementation for the FacilityExternalVisitor service. Represents a row in the &quot;Facility_External_Visitor&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link FacilityExternalVisitorImpl}.
 * </p>
 *
 * @author CloudSmartz
 * @see FacilityExternalVisitorImpl
 * @see com.pacnet.connect.model.FacilityExternalVisitor
 * @generated
 */
public abstract class FacilityExternalVisitorBaseImpl
	extends FacilityExternalVisitorModelImpl implements FacilityExternalVisitor {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a facility external visitor model instance should use the {@link FacilityExternalVisitor} interface instead.
	 */
	public void persist() throws SystemException {
		if (this.isNew()) {
			FacilityExternalVisitorLocalServiceUtil.addFacilityExternalVisitor(this);
		}
		else {
			FacilityExternalVisitorLocalServiceUtil.updateFacilityExternalVisitor(this);
		}
	}
}