/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.pacnet.connect.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import com.pacnet.connect.model.FacilitySecurityOfficerMapping;
import com.pacnet.connect.model.FacilitySecurityOfficerMappingModel;
import com.pacnet.connect.model.FacilitySecurityOfficerMappingSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the FacilitySecurityOfficerMapping service. Represents a row in the &quot;Facility_Security_Officer_Mapping&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.pacnet.connect.model.FacilitySecurityOfficerMappingModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link FacilitySecurityOfficerMappingImpl}.
 * </p>
 *
 * @author CloudSmartz
 * @see FacilitySecurityOfficerMappingImpl
 * @see com.pacnet.connect.model.FacilitySecurityOfficerMapping
 * @see com.pacnet.connect.model.FacilitySecurityOfficerMappingModel
 * @generated
 */
@JSON(strict = true)
public class FacilitySecurityOfficerMappingModelImpl extends BaseModelImpl<FacilitySecurityOfficerMapping>
	implements FacilitySecurityOfficerMappingModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a facility security officer mapping model instance should use the {@link com.pacnet.connect.model.FacilitySecurityOfficerMapping} interface instead.
	 */
	public static final String TABLE_NAME = "Facility_Security_Officer_Mapping";
	public static final Object[][] TABLE_COLUMNS = {
			{ "ID", Types.BIGINT },
			{ "Facility_ID", Types.BIGINT },
			{ "Security_Officer_User_ID", Types.BIGINT },
			{ "IsActive", Types.BOOLEAN },
			{ "Created_On", Types.TIMESTAMP },
			{ "Created_By", Types.VARCHAR },
			{ "Updated_On", Types.TIMESTAMP },
			{ "Updated_By", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table Facility_Security_Officer_Mapping (ID LONG not null primary key IDENTITY,Facility_ID LONG,Security_Officer_User_ID LONG,IsActive BOOLEAN,Created_On DATE null,Created_By VARCHAR(75) null,Updated_On DATE null,Updated_By VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table Facility_Security_Officer_Mapping";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.pacnet.connect.model.FacilitySecurityOfficerMapping"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.pacnet.connect.model.FacilitySecurityOfficerMapping"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.pacnet.connect.model.FacilitySecurityOfficerMapping"),
			true);
	public static long FACILTYID_COLUMN_BITMASK = 1L;
	public static long SECURITYOFFICERUSERID_COLUMN_BITMASK = 2L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static FacilitySecurityOfficerMapping toModel(
		FacilitySecurityOfficerMappingSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		FacilitySecurityOfficerMapping model = new FacilitySecurityOfficerMappingImpl();

		model.setId(soapModel.getId());
		model.setFaciltyId(soapModel.getFaciltyId());
		model.setSecurityOfficerUserId(soapModel.getSecurityOfficerUserId());
		model.setIsActive(soapModel.getIsActive());
		model.setCreatedOn(soapModel.getCreatedOn());
		model.setCreatedBy(soapModel.getCreatedBy());
		model.setUpdatedOn(soapModel.getUpdatedOn());
		model.setUpdatedBy(soapModel.getUpdatedBy());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<FacilitySecurityOfficerMapping> toModels(
		FacilitySecurityOfficerMappingSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<FacilitySecurityOfficerMapping> models = new ArrayList<FacilitySecurityOfficerMapping>(soapModels.length);

		for (FacilitySecurityOfficerMappingSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.pacnet.connect.model.FacilitySecurityOfficerMapping"));

	public FacilitySecurityOfficerMappingModelImpl() {
	}

	public long getPrimaryKey() {
		return _id;
	}

	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_id);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return FacilitySecurityOfficerMapping.class;
	}

	public String getModelClassName() {
		return FacilitySecurityOfficerMapping.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("id", getId());
		attributes.put("faciltyId", getFaciltyId());
		attributes.put("securityOfficerUserId", getSecurityOfficerUserId());
		attributes.put("isActive", getIsActive());
		attributes.put("createdOn", getCreatedOn());
		attributes.put("createdBy", getCreatedBy());
		attributes.put("updatedOn", getUpdatedOn());
		attributes.put("updatedBy", getUpdatedBy());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long id = (Long)attributes.get("id");

		if (id != null) {
			setId(id);
		}

		Long faciltyId = (Long)attributes.get("faciltyId");

		if (faciltyId != null) {
			setFaciltyId(faciltyId);
		}

		Long securityOfficerUserId = (Long)attributes.get(
				"securityOfficerUserId");

		if (securityOfficerUserId != null) {
			setSecurityOfficerUserId(securityOfficerUserId);
		}

		Boolean isActive = (Boolean)attributes.get("isActive");

		if (isActive != null) {
			setIsActive(isActive);
		}

		Date createdOn = (Date)attributes.get("createdOn");

		if (createdOn != null) {
			setCreatedOn(createdOn);
		}

		String createdBy = (String)attributes.get("createdBy");

		if (createdBy != null) {
			setCreatedBy(createdBy);
		}

		Date updatedOn = (Date)attributes.get("updatedOn");

		if (updatedOn != null) {
			setUpdatedOn(updatedOn);
		}

		String updatedBy = (String)attributes.get("updatedBy");

		if (updatedBy != null) {
			setUpdatedBy(updatedBy);
		}
	}

	@JSON
	public long getId() {
		return _id;
	}

	public void setId(long id) {
		_id = id;
	}

	@JSON
	public long getFaciltyId() {
		return _faciltyId;
	}

	public void setFaciltyId(long faciltyId) {
		_columnBitmask |= FACILTYID_COLUMN_BITMASK;

		if (!_setOriginalFaciltyId) {
			_setOriginalFaciltyId = true;

			_originalFaciltyId = _faciltyId;
		}

		_faciltyId = faciltyId;
	}

	public long getOriginalFaciltyId() {
		return _originalFaciltyId;
	}

	@JSON
	public long getSecurityOfficerUserId() {
		return _securityOfficerUserId;
	}

	public void setSecurityOfficerUserId(long securityOfficerUserId) {
		_columnBitmask |= SECURITYOFFICERUSERID_COLUMN_BITMASK;

		if (!_setOriginalSecurityOfficerUserId) {
			_setOriginalSecurityOfficerUserId = true;

			_originalSecurityOfficerUserId = _securityOfficerUserId;
		}

		_securityOfficerUserId = securityOfficerUserId;
	}

	public String getSecurityOfficerUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getSecurityOfficerUserId(), "uuid",
			_securityOfficerUserUuid);
	}

	public void setSecurityOfficerUserUuid(String securityOfficerUserUuid) {
		_securityOfficerUserUuid = securityOfficerUserUuid;
	}

	public long getOriginalSecurityOfficerUserId() {
		return _originalSecurityOfficerUserId;
	}

	@JSON
	public boolean getIsActive() {
		return _isActive;
	}

	public boolean isIsActive() {
		return _isActive;
	}

	public void setIsActive(boolean isActive) {
		_isActive = isActive;
	}

	@JSON
	public Date getCreatedOn() {
		return _createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		_createdOn = createdOn;
	}

	@JSON
	public String getCreatedBy() {
		if (_createdBy == null) {
			return StringPool.BLANK;
		}
		else {
			return _createdBy;
		}
	}

	public void setCreatedBy(String createdBy) {
		_createdBy = createdBy;
	}

	@JSON
	public Date getUpdatedOn() {
		return _updatedOn;
	}

	public void setUpdatedOn(Date updatedOn) {
		_updatedOn = updatedOn;
	}

	@JSON
	public String getUpdatedBy() {
		if (_updatedBy == null) {
			return StringPool.BLANK;
		}
		else {
			return _updatedBy;
		}
	}

	public void setUpdatedBy(String updatedBy) {
		_updatedBy = updatedBy;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			FacilitySecurityOfficerMapping.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public FacilitySecurityOfficerMapping toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (FacilitySecurityOfficerMapping)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public Object clone() {
		FacilitySecurityOfficerMappingImpl facilitySecurityOfficerMappingImpl = new FacilitySecurityOfficerMappingImpl();

		facilitySecurityOfficerMappingImpl.setId(getId());
		facilitySecurityOfficerMappingImpl.setFaciltyId(getFaciltyId());
		facilitySecurityOfficerMappingImpl.setSecurityOfficerUserId(getSecurityOfficerUserId());
		facilitySecurityOfficerMappingImpl.setIsActive(getIsActive());
		facilitySecurityOfficerMappingImpl.setCreatedOn(getCreatedOn());
		facilitySecurityOfficerMappingImpl.setCreatedBy(getCreatedBy());
		facilitySecurityOfficerMappingImpl.setUpdatedOn(getUpdatedOn());
		facilitySecurityOfficerMappingImpl.setUpdatedBy(getUpdatedBy());

		facilitySecurityOfficerMappingImpl.resetOriginalValues();

		return facilitySecurityOfficerMappingImpl;
	}

	public int compareTo(
		FacilitySecurityOfficerMapping facilitySecurityOfficerMapping) {
		long primaryKey = facilitySecurityOfficerMapping.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		FacilitySecurityOfficerMapping facilitySecurityOfficerMapping = null;

		try {
			facilitySecurityOfficerMapping = (FacilitySecurityOfficerMapping)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long primaryKey = facilitySecurityOfficerMapping.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		FacilitySecurityOfficerMappingModelImpl facilitySecurityOfficerMappingModelImpl =
			this;

		facilitySecurityOfficerMappingModelImpl._originalFaciltyId = facilitySecurityOfficerMappingModelImpl._faciltyId;

		facilitySecurityOfficerMappingModelImpl._setOriginalFaciltyId = false;

		facilitySecurityOfficerMappingModelImpl._originalSecurityOfficerUserId = facilitySecurityOfficerMappingModelImpl._securityOfficerUserId;

		facilitySecurityOfficerMappingModelImpl._setOriginalSecurityOfficerUserId = false;

		facilitySecurityOfficerMappingModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<FacilitySecurityOfficerMapping> toCacheModel() {
		FacilitySecurityOfficerMappingCacheModel facilitySecurityOfficerMappingCacheModel =
			new FacilitySecurityOfficerMappingCacheModel();

		facilitySecurityOfficerMappingCacheModel.id = getId();

		facilitySecurityOfficerMappingCacheModel.faciltyId = getFaciltyId();

		facilitySecurityOfficerMappingCacheModel.securityOfficerUserId = getSecurityOfficerUserId();

		facilitySecurityOfficerMappingCacheModel.isActive = getIsActive();

		Date createdOn = getCreatedOn();

		if (createdOn != null) {
			facilitySecurityOfficerMappingCacheModel.createdOn = createdOn.getTime();
		}
		else {
			facilitySecurityOfficerMappingCacheModel.createdOn = Long.MIN_VALUE;
		}

		facilitySecurityOfficerMappingCacheModel.createdBy = getCreatedBy();

		String createdBy = facilitySecurityOfficerMappingCacheModel.createdBy;

		if ((createdBy != null) && (createdBy.length() == 0)) {
			facilitySecurityOfficerMappingCacheModel.createdBy = null;
		}

		Date updatedOn = getUpdatedOn();

		if (updatedOn != null) {
			facilitySecurityOfficerMappingCacheModel.updatedOn = updatedOn.getTime();
		}
		else {
			facilitySecurityOfficerMappingCacheModel.updatedOn = Long.MIN_VALUE;
		}

		facilitySecurityOfficerMappingCacheModel.updatedBy = getUpdatedBy();

		String updatedBy = facilitySecurityOfficerMappingCacheModel.updatedBy;

		if ((updatedBy != null) && (updatedBy.length() == 0)) {
			facilitySecurityOfficerMappingCacheModel.updatedBy = null;
		}

		return facilitySecurityOfficerMappingCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(17);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", faciltyId=");
		sb.append(getFaciltyId());
		sb.append(", securityOfficerUserId=");
		sb.append(getSecurityOfficerUserId());
		sb.append(", isActive=");
		sb.append(getIsActive());
		sb.append(", createdOn=");
		sb.append(getCreatedOn());
		sb.append(", createdBy=");
		sb.append(getCreatedBy());
		sb.append(", updatedOn=");
		sb.append(getUpdatedOn());
		sb.append(", updatedBy=");
		sb.append(getUpdatedBy());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(28);

		sb.append("<model><model-name>");
		sb.append("com.pacnet.connect.model.FacilitySecurityOfficerMapping");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>faciltyId</column-name><column-value><![CDATA[");
		sb.append(getFaciltyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>securityOfficerUserId</column-name><column-value><![CDATA[");
		sb.append(getSecurityOfficerUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>isActive</column-name><column-value><![CDATA[");
		sb.append(getIsActive());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createdOn</column-name><column-value><![CDATA[");
		sb.append(getCreatedOn());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createdBy</column-name><column-value><![CDATA[");
		sb.append(getCreatedBy());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>updatedOn</column-name><column-value><![CDATA[");
		sb.append(getUpdatedOn());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>updatedBy</column-name><column-value><![CDATA[");
		sb.append(getUpdatedBy());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = FacilitySecurityOfficerMapping.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			FacilitySecurityOfficerMapping.class
		};
	private long _id;
	private long _faciltyId;
	private long _originalFaciltyId;
	private boolean _setOriginalFaciltyId;
	private long _securityOfficerUserId;
	private String _securityOfficerUserUuid;
	private long _originalSecurityOfficerUserId;
	private boolean _setOriginalSecurityOfficerUserId;
	private boolean _isActive;
	private Date _createdOn;
	private String _createdBy;
	private Date _updatedOn;
	private String _updatedBy;
	private long _columnBitmask;
	private FacilitySecurityOfficerMapping _escapedModelProxy;
}