/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.pacnet.connect.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import com.pacnet.connect.model.FacilityStaffMapping;
import com.pacnet.connect.model.FacilityStaffMappingModel;
import com.pacnet.connect.model.FacilityStaffMappingSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the FacilityStaffMapping service. Represents a row in the &quot;Facility_Staff_Mapping&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.pacnet.connect.model.FacilityStaffMappingModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link FacilityStaffMappingImpl}.
 * </p>
 *
 * @author CloudSmartz
 * @see FacilityStaffMappingImpl
 * @see com.pacnet.connect.model.FacilityStaffMapping
 * @see com.pacnet.connect.model.FacilityStaffMappingModel
 * @generated
 */
@JSON(strict = true)
public class FacilityStaffMappingModelImpl extends BaseModelImpl<FacilityStaffMapping>
	implements FacilityStaffMappingModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a facility staff mapping model instance should use the {@link com.pacnet.connect.model.FacilityStaffMapping} interface instead.
	 */
	public static final String TABLE_NAME = "Facility_Staff_Mapping";
	public static final Object[][] TABLE_COLUMNS = {
			{ "ID", Types.BIGINT },
			{ "Facility_ID", Types.BIGINT },
			{ "Staff_User_ID", Types.BIGINT },
			{ "IsActive", Types.BOOLEAN },
			{ "Created_On", Types.TIMESTAMP },
			{ "Created_By", Types.VARCHAR },
			{ "Updated_On", Types.TIMESTAMP },
			{ "Updated_By", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table Facility_Staff_Mapping (ID LONG not null primary key IDENTITY,Facility_ID LONG,Staff_User_ID LONG,IsActive BOOLEAN,Created_On DATE null,Created_By VARCHAR(75) null,Updated_On DATE null,Updated_By VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table Facility_Staff_Mapping";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.pacnet.connect.model.FacilityStaffMapping"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.pacnet.connect.model.FacilityStaffMapping"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.pacnet.connect.model.FacilityStaffMapping"),
			true);
	public static long FACILITYID_COLUMN_BITMASK = 1L;
	public static long STAFFUSERID_COLUMN_BITMASK = 2L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static FacilityStaffMapping toModel(
		FacilityStaffMappingSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		FacilityStaffMapping model = new FacilityStaffMappingImpl();

		model.setId(soapModel.getId());
		model.setFacilityId(soapModel.getFacilityId());
		model.setStaffUserId(soapModel.getStaffUserId());
		model.setIsActive(soapModel.getIsActive());
		model.setCreatedOn(soapModel.getCreatedOn());
		model.setCreatedBy(soapModel.getCreatedBy());
		model.setUpdatedOn(soapModel.getUpdatedOn());
		model.setUpdatedBy(soapModel.getUpdatedBy());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<FacilityStaffMapping> toModels(
		FacilityStaffMappingSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<FacilityStaffMapping> models = new ArrayList<FacilityStaffMapping>(soapModels.length);

		for (FacilityStaffMappingSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.pacnet.connect.model.FacilityStaffMapping"));

	public FacilityStaffMappingModelImpl() {
	}

	public long getPrimaryKey() {
		return _id;
	}

	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_id);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return FacilityStaffMapping.class;
	}

	public String getModelClassName() {
		return FacilityStaffMapping.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("id", getId());
		attributes.put("facilityId", getFacilityId());
		attributes.put("staffUserId", getStaffUserId());
		attributes.put("isActive", getIsActive());
		attributes.put("createdOn", getCreatedOn());
		attributes.put("createdBy", getCreatedBy());
		attributes.put("updatedOn", getUpdatedOn());
		attributes.put("updatedBy", getUpdatedBy());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long id = (Long)attributes.get("id");

		if (id != null) {
			setId(id);
		}

		Long facilityId = (Long)attributes.get("facilityId");

		if (facilityId != null) {
			setFacilityId(facilityId);
		}

		Long staffUserId = (Long)attributes.get("staffUserId");

		if (staffUserId != null) {
			setStaffUserId(staffUserId);
		}

		Boolean isActive = (Boolean)attributes.get("isActive");

		if (isActive != null) {
			setIsActive(isActive);
		}

		Date createdOn = (Date)attributes.get("createdOn");

		if (createdOn != null) {
			setCreatedOn(createdOn);
		}

		String createdBy = (String)attributes.get("createdBy");

		if (createdBy != null) {
			setCreatedBy(createdBy);
		}

		Date updatedOn = (Date)attributes.get("updatedOn");

		if (updatedOn != null) {
			setUpdatedOn(updatedOn);
		}

		String updatedBy = (String)attributes.get("updatedBy");

		if (updatedBy != null) {
			setUpdatedBy(updatedBy);
		}
	}

	@JSON
	public long getId() {
		return _id;
	}

	public void setId(long id) {
		_id = id;
	}

	@JSON
	public long getFacilityId() {
		return _facilityId;
	}

	public void setFacilityId(long facilityId) {
		_columnBitmask |= FACILITYID_COLUMN_BITMASK;

		if (!_setOriginalFacilityId) {
			_setOriginalFacilityId = true;

			_originalFacilityId = _facilityId;
		}

		_facilityId = facilityId;
	}

	public long getOriginalFacilityId() {
		return _originalFacilityId;
	}

	@JSON
	public long getStaffUserId() {
		return _staffUserId;
	}

	public void setStaffUserId(long staffUserId) {
		_columnBitmask |= STAFFUSERID_COLUMN_BITMASK;

		if (!_setOriginalStaffUserId) {
			_setOriginalStaffUserId = true;

			_originalStaffUserId = _staffUserId;
		}

		_staffUserId = staffUserId;
	}

	public String getStaffUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getStaffUserId(), "uuid", _staffUserUuid);
	}

	public void setStaffUserUuid(String staffUserUuid) {
		_staffUserUuid = staffUserUuid;
	}

	public long getOriginalStaffUserId() {
		return _originalStaffUserId;
	}

	@JSON
	public boolean getIsActive() {
		return _isActive;
	}

	public boolean isIsActive() {
		return _isActive;
	}

	public void setIsActive(boolean isActive) {
		_isActive = isActive;
	}

	@JSON
	public Date getCreatedOn() {
		return _createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		_createdOn = createdOn;
	}

	@JSON
	public String getCreatedBy() {
		if (_createdBy == null) {
			return StringPool.BLANK;
		}
		else {
			return _createdBy;
		}
	}

	public void setCreatedBy(String createdBy) {
		_createdBy = createdBy;
	}

	@JSON
	public Date getUpdatedOn() {
		return _updatedOn;
	}

	public void setUpdatedOn(Date updatedOn) {
		_updatedOn = updatedOn;
	}

	@JSON
	public String getUpdatedBy() {
		if (_updatedBy == null) {
			return StringPool.BLANK;
		}
		else {
			return _updatedBy;
		}
	}

	public void setUpdatedBy(String updatedBy) {
		_updatedBy = updatedBy;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			FacilityStaffMapping.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public FacilityStaffMapping toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (FacilityStaffMapping)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public Object clone() {
		FacilityStaffMappingImpl facilityStaffMappingImpl = new FacilityStaffMappingImpl();

		facilityStaffMappingImpl.setId(getId());
		facilityStaffMappingImpl.setFacilityId(getFacilityId());
		facilityStaffMappingImpl.setStaffUserId(getStaffUserId());
		facilityStaffMappingImpl.setIsActive(getIsActive());
		facilityStaffMappingImpl.setCreatedOn(getCreatedOn());
		facilityStaffMappingImpl.setCreatedBy(getCreatedBy());
		facilityStaffMappingImpl.setUpdatedOn(getUpdatedOn());
		facilityStaffMappingImpl.setUpdatedBy(getUpdatedBy());

		facilityStaffMappingImpl.resetOriginalValues();

		return facilityStaffMappingImpl;
	}

	public int compareTo(FacilityStaffMapping facilityStaffMapping) {
		long primaryKey = facilityStaffMapping.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		FacilityStaffMapping facilityStaffMapping = null;

		try {
			facilityStaffMapping = (FacilityStaffMapping)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long primaryKey = facilityStaffMapping.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		FacilityStaffMappingModelImpl facilityStaffMappingModelImpl = this;

		facilityStaffMappingModelImpl._originalFacilityId = facilityStaffMappingModelImpl._facilityId;

		facilityStaffMappingModelImpl._setOriginalFacilityId = false;

		facilityStaffMappingModelImpl._originalStaffUserId = facilityStaffMappingModelImpl._staffUserId;

		facilityStaffMappingModelImpl._setOriginalStaffUserId = false;

		facilityStaffMappingModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<FacilityStaffMapping> toCacheModel() {
		FacilityStaffMappingCacheModel facilityStaffMappingCacheModel = new FacilityStaffMappingCacheModel();

		facilityStaffMappingCacheModel.id = getId();

		facilityStaffMappingCacheModel.facilityId = getFacilityId();

		facilityStaffMappingCacheModel.staffUserId = getStaffUserId();

		facilityStaffMappingCacheModel.isActive = getIsActive();

		Date createdOn = getCreatedOn();

		if (createdOn != null) {
			facilityStaffMappingCacheModel.createdOn = createdOn.getTime();
		}
		else {
			facilityStaffMappingCacheModel.createdOn = Long.MIN_VALUE;
		}

		facilityStaffMappingCacheModel.createdBy = getCreatedBy();

		String createdBy = facilityStaffMappingCacheModel.createdBy;

		if ((createdBy != null) && (createdBy.length() == 0)) {
			facilityStaffMappingCacheModel.createdBy = null;
		}

		Date updatedOn = getUpdatedOn();

		if (updatedOn != null) {
			facilityStaffMappingCacheModel.updatedOn = updatedOn.getTime();
		}
		else {
			facilityStaffMappingCacheModel.updatedOn = Long.MIN_VALUE;
		}

		facilityStaffMappingCacheModel.updatedBy = getUpdatedBy();

		String updatedBy = facilityStaffMappingCacheModel.updatedBy;

		if ((updatedBy != null) && (updatedBy.length() == 0)) {
			facilityStaffMappingCacheModel.updatedBy = null;
		}

		return facilityStaffMappingCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(17);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", facilityId=");
		sb.append(getFacilityId());
		sb.append(", staffUserId=");
		sb.append(getStaffUserId());
		sb.append(", isActive=");
		sb.append(getIsActive());
		sb.append(", createdOn=");
		sb.append(getCreatedOn());
		sb.append(", createdBy=");
		sb.append(getCreatedBy());
		sb.append(", updatedOn=");
		sb.append(getUpdatedOn());
		sb.append(", updatedBy=");
		sb.append(getUpdatedBy());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(28);

		sb.append("<model><model-name>");
		sb.append("com.pacnet.connect.model.FacilityStaffMapping");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>facilityId</column-name><column-value><![CDATA[");
		sb.append(getFacilityId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>staffUserId</column-name><column-value><![CDATA[");
		sb.append(getStaffUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>isActive</column-name><column-value><![CDATA[");
		sb.append(getIsActive());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createdOn</column-name><column-value><![CDATA[");
		sb.append(getCreatedOn());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createdBy</column-name><column-value><![CDATA[");
		sb.append(getCreatedBy());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>updatedOn</column-name><column-value><![CDATA[");
		sb.append(getUpdatedOn());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>updatedBy</column-name><column-value><![CDATA[");
		sb.append(getUpdatedBy());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = FacilityStaffMapping.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			FacilityStaffMapping.class
		};
	private long _id;
	private long _facilityId;
	private long _originalFacilityId;
	private boolean _setOriginalFacilityId;
	private long _staffUserId;
	private String _staffUserUuid;
	private long _originalStaffUserId;
	private boolean _setOriginalStaffUserId;
	private boolean _isActive;
	private Date _createdOn;
	private String _createdBy;
	private Date _updatedOn;
	private String _updatedBy;
	private long _columnBitmask;
	private FacilityStaffMapping _escapedModelProxy;
}