/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.pacnet.connect.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import com.pacnet.connect.model.FacilityUserService;
import com.pacnet.connect.model.FacilityUserServiceModel;
import com.pacnet.connect.model.FacilityUserServiceSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the FacilityUserService service. Represents a row in the &quot;Facility_User_Service_Mapping&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.pacnet.connect.model.FacilityUserServiceModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link FacilityUserServiceImpl}.
 * </p>
 *
 * @author CloudSmartz
 * @see FacilityUserServiceImpl
 * @see com.pacnet.connect.model.FacilityUserService
 * @see com.pacnet.connect.model.FacilityUserServiceModel
 * @generated
 */
@JSON(strict = true)
public class FacilityUserServiceModelImpl extends BaseModelImpl<FacilityUserService>
	implements FacilityUserServiceModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a facility user service model instance should use the {@link com.pacnet.connect.model.FacilityUserService} interface instead.
	 */
	public static final String TABLE_NAME = "Facility_User_Service_Mapping";
	public static final Object[][] TABLE_COLUMNS = {
			{ "ID", Types.BIGINT },
			{ "Facility_User_Mapping_ID", Types.BIGINT },
			{ "Facility_Service_ID", Types.BIGINT },
			{ "IsActive", Types.BOOLEAN },
			{ "Created_On", Types.TIMESTAMP },
			{ "Created_By", Types.VARCHAR },
			{ "Updated_On", Types.TIMESTAMP },
			{ "Updated_By", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table Facility_User_Service_Mapping (ID LONG not null primary key IDENTITY,Facility_User_Mapping_ID LONG,Facility_Service_ID LONG,IsActive BOOLEAN,Created_On DATE null,Created_By VARCHAR(75) null,Updated_On DATE null,Updated_By VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table Facility_User_Service_Mapping";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.pacnet.connect.model.FacilityUserService"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.pacnet.connect.model.FacilityUserService"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.pacnet.connect.model.FacilityUserService"),
			true);
	public static long FACILITYSERVICEID_COLUMN_BITMASK = 1L;
	public static long FACILITYUSERMAPPINGID_COLUMN_BITMASK = 2L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static FacilityUserService toModel(FacilityUserServiceSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		FacilityUserService model = new FacilityUserServiceImpl();

		model.setId(soapModel.getId());
		model.setFacilityUserMappingId(soapModel.getFacilityUserMappingId());
		model.setFacilityServiceId(soapModel.getFacilityServiceId());
		model.setIsActive(soapModel.getIsActive());
		model.setCreatedOn(soapModel.getCreatedOn());
		model.setCreatedBy(soapModel.getCreatedBy());
		model.setUpdatedOn(soapModel.getUpdatedOn());
		model.setUpdatedBy(soapModel.getUpdatedBy());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<FacilityUserService> toModels(
		FacilityUserServiceSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<FacilityUserService> models = new ArrayList<FacilityUserService>(soapModels.length);

		for (FacilityUserServiceSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.pacnet.connect.model.FacilityUserService"));

	public FacilityUserServiceModelImpl() {
	}

	public long getPrimaryKey() {
		return _id;
	}

	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_id);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return FacilityUserService.class;
	}

	public String getModelClassName() {
		return FacilityUserService.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("id", getId());
		attributes.put("facilityUserMappingId", getFacilityUserMappingId());
		attributes.put("facilityServiceId", getFacilityServiceId());
		attributes.put("isActive", getIsActive());
		attributes.put("createdOn", getCreatedOn());
		attributes.put("createdBy", getCreatedBy());
		attributes.put("updatedOn", getUpdatedOn());
		attributes.put("updatedBy", getUpdatedBy());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long id = (Long)attributes.get("id");

		if (id != null) {
			setId(id);
		}

		Long facilityUserMappingId = (Long)attributes.get(
				"facilityUserMappingId");

		if (facilityUserMappingId != null) {
			setFacilityUserMappingId(facilityUserMappingId);
		}

		Long facilityServiceId = (Long)attributes.get("facilityServiceId");

		if (facilityServiceId != null) {
			setFacilityServiceId(facilityServiceId);
		}

		Boolean isActive = (Boolean)attributes.get("isActive");

		if (isActive != null) {
			setIsActive(isActive);
		}

		Date createdOn = (Date)attributes.get("createdOn");

		if (createdOn != null) {
			setCreatedOn(createdOn);
		}

		String createdBy = (String)attributes.get("createdBy");

		if (createdBy != null) {
			setCreatedBy(createdBy);
		}

		Date updatedOn = (Date)attributes.get("updatedOn");

		if (updatedOn != null) {
			setUpdatedOn(updatedOn);
		}

		String updatedBy = (String)attributes.get("updatedBy");

		if (updatedBy != null) {
			setUpdatedBy(updatedBy);
		}
	}

	@JSON
	public long getId() {
		return _id;
	}

	public void setId(long id) {
		_id = id;
	}

	@JSON
	public long getFacilityUserMappingId() {
		return _facilityUserMappingId;
	}

	public void setFacilityUserMappingId(long facilityUserMappingId) {
		_columnBitmask |= FACILITYUSERMAPPINGID_COLUMN_BITMASK;

		if (!_setOriginalFacilityUserMappingId) {
			_setOriginalFacilityUserMappingId = true;

			_originalFacilityUserMappingId = _facilityUserMappingId;
		}

		_facilityUserMappingId = facilityUserMappingId;
	}

	public long getOriginalFacilityUserMappingId() {
		return _originalFacilityUserMappingId;
	}

	@JSON
	public long getFacilityServiceId() {
		return _facilityServiceId;
	}

	public void setFacilityServiceId(long facilityServiceId) {
		_columnBitmask |= FACILITYSERVICEID_COLUMN_BITMASK;

		if (!_setOriginalFacilityServiceId) {
			_setOriginalFacilityServiceId = true;

			_originalFacilityServiceId = _facilityServiceId;
		}

		_facilityServiceId = facilityServiceId;
	}

	public long getOriginalFacilityServiceId() {
		return _originalFacilityServiceId;
	}

	@JSON
	public boolean getIsActive() {
		return _isActive;
	}

	public boolean isIsActive() {
		return _isActive;
	}

	public void setIsActive(boolean isActive) {
		_isActive = isActive;
	}

	@JSON
	public Date getCreatedOn() {
		return _createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		_createdOn = createdOn;
	}

	@JSON
	public String getCreatedBy() {
		if (_createdBy == null) {
			return StringPool.BLANK;
		}
		else {
			return _createdBy;
		}
	}

	public void setCreatedBy(String createdBy) {
		_createdBy = createdBy;
	}

	@JSON
	public Date getUpdatedOn() {
		return _updatedOn;
	}

	public void setUpdatedOn(Date updatedOn) {
		_updatedOn = updatedOn;
	}

	@JSON
	public String getUpdatedBy() {
		if (_updatedBy == null) {
			return StringPool.BLANK;
		}
		else {
			return _updatedBy;
		}
	}

	public void setUpdatedBy(String updatedBy) {
		_updatedBy = updatedBy;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			FacilityUserService.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public FacilityUserService toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (FacilityUserService)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public Object clone() {
		FacilityUserServiceImpl facilityUserServiceImpl = new FacilityUserServiceImpl();

		facilityUserServiceImpl.setId(getId());
		facilityUserServiceImpl.setFacilityUserMappingId(getFacilityUserMappingId());
		facilityUserServiceImpl.setFacilityServiceId(getFacilityServiceId());
		facilityUserServiceImpl.setIsActive(getIsActive());
		facilityUserServiceImpl.setCreatedOn(getCreatedOn());
		facilityUserServiceImpl.setCreatedBy(getCreatedBy());
		facilityUserServiceImpl.setUpdatedOn(getUpdatedOn());
		facilityUserServiceImpl.setUpdatedBy(getUpdatedBy());

		facilityUserServiceImpl.resetOriginalValues();

		return facilityUserServiceImpl;
	}

	public int compareTo(FacilityUserService facilityUserService) {
		long primaryKey = facilityUserService.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		FacilityUserService facilityUserService = null;

		try {
			facilityUserService = (FacilityUserService)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long primaryKey = facilityUserService.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		FacilityUserServiceModelImpl facilityUserServiceModelImpl = this;

		facilityUserServiceModelImpl._originalFacilityUserMappingId = facilityUserServiceModelImpl._facilityUserMappingId;

		facilityUserServiceModelImpl._setOriginalFacilityUserMappingId = false;

		facilityUserServiceModelImpl._originalFacilityServiceId = facilityUserServiceModelImpl._facilityServiceId;

		facilityUserServiceModelImpl._setOriginalFacilityServiceId = false;

		facilityUserServiceModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<FacilityUserService> toCacheModel() {
		FacilityUserServiceCacheModel facilityUserServiceCacheModel = new FacilityUserServiceCacheModel();

		facilityUserServiceCacheModel.id = getId();

		facilityUserServiceCacheModel.facilityUserMappingId = getFacilityUserMappingId();

		facilityUserServiceCacheModel.facilityServiceId = getFacilityServiceId();

		facilityUserServiceCacheModel.isActive = getIsActive();

		Date createdOn = getCreatedOn();

		if (createdOn != null) {
			facilityUserServiceCacheModel.createdOn = createdOn.getTime();
		}
		else {
			facilityUserServiceCacheModel.createdOn = Long.MIN_VALUE;
		}

		facilityUserServiceCacheModel.createdBy = getCreatedBy();

		String createdBy = facilityUserServiceCacheModel.createdBy;

		if ((createdBy != null) && (createdBy.length() == 0)) {
			facilityUserServiceCacheModel.createdBy = null;
		}

		Date updatedOn = getUpdatedOn();

		if (updatedOn != null) {
			facilityUserServiceCacheModel.updatedOn = updatedOn.getTime();
		}
		else {
			facilityUserServiceCacheModel.updatedOn = Long.MIN_VALUE;
		}

		facilityUserServiceCacheModel.updatedBy = getUpdatedBy();

		String updatedBy = facilityUserServiceCacheModel.updatedBy;

		if ((updatedBy != null) && (updatedBy.length() == 0)) {
			facilityUserServiceCacheModel.updatedBy = null;
		}

		return facilityUserServiceCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(17);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", facilityUserMappingId=");
		sb.append(getFacilityUserMappingId());
		sb.append(", facilityServiceId=");
		sb.append(getFacilityServiceId());
		sb.append(", isActive=");
		sb.append(getIsActive());
		sb.append(", createdOn=");
		sb.append(getCreatedOn());
		sb.append(", createdBy=");
		sb.append(getCreatedBy());
		sb.append(", updatedOn=");
		sb.append(getUpdatedOn());
		sb.append(", updatedBy=");
		sb.append(getUpdatedBy());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(28);

		sb.append("<model><model-name>");
		sb.append("com.pacnet.connect.model.FacilityUserService");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>facilityUserMappingId</column-name><column-value><![CDATA[");
		sb.append(getFacilityUserMappingId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>facilityServiceId</column-name><column-value><![CDATA[");
		sb.append(getFacilityServiceId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>isActive</column-name><column-value><![CDATA[");
		sb.append(getIsActive());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createdOn</column-name><column-value><![CDATA[");
		sb.append(getCreatedOn());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createdBy</column-name><column-value><![CDATA[");
		sb.append(getCreatedBy());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>updatedOn</column-name><column-value><![CDATA[");
		sb.append(getUpdatedOn());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>updatedBy</column-name><column-value><![CDATA[");
		sb.append(getUpdatedBy());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = FacilityUserService.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			FacilityUserService.class
		};
	private long _id;
	private long _facilityUserMappingId;
	private long _originalFacilityUserMappingId;
	private boolean _setOriginalFacilityUserMappingId;
	private long _facilityServiceId;
	private long _originalFacilityServiceId;
	private boolean _setOriginalFacilityServiceId;
	private boolean _isActive;
	private Date _createdOn;
	private String _createdBy;
	private Date _updatedOn;
	private String _updatedBy;
	private long _columnBitmask;
	private FacilityUserService _escapedModelProxy;
}