/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.pacnet.connect.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import com.pacnet.connect.model.SMAAdmins;
import com.pacnet.connect.model.SMAAdminsModel;
import com.pacnet.connect.model.SMAAdminsSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the SMAAdmins service. Represents a row in the &quot;PA_SMA_admins&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.pacnet.connect.model.SMAAdminsModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SMAAdminsImpl}.
 * </p>
 *
 * @author CloudSmartz
 * @see SMAAdminsImpl
 * @see com.pacnet.connect.model.SMAAdmins
 * @see com.pacnet.connect.model.SMAAdminsModel
 * @generated
 */
@JSON(strict = true)
public class SMAAdminsModelImpl extends BaseModelImpl<SMAAdmins>
	implements SMAAdminsModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a s m a admins model instance should use the {@link com.pacnet.connect.model.SMAAdmins} interface instead.
	 */
	public static final String TABLE_NAME = "PA_SMA_admins";
	public static final Object[][] TABLE_COLUMNS = {
			{ "id", Types.BIGINT },
			{ "user_id", Types.BIGINT },
			{ "radcheck_id", Types.BIGINT },
			{ "company_id", Types.BIGINT },
			{ "IsActive", Types.INTEGER },
			{ "Created_On", Types.TIMESTAMP },
			{ "Created_By", Types.VARCHAR },
			{ "Updated_On", Types.TIMESTAMP },
			{ "Updated_By", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table PA_SMA_admins (id LONG not null primary key IDENTITY,user_id LONG,radcheck_id LONG,company_id LONG,IsActive INTEGER,Created_On DATE null,Created_By VARCHAR(75) null,Updated_On DATE null,Updated_By VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table PA_SMA_admins";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.pacnet.connect.model.SMAAdmins"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.pacnet.connect.model.SMAAdmins"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.pacnet.connect.model.SMAAdmins"),
			true);
	public static long COMPANYID_COLUMN_BITMASK = 1L;
	public static long ISACTIVE_COLUMN_BITMASK = 2L;
	public static long RADCHECKID_COLUMN_BITMASK = 4L;
	public static long USERID_COLUMN_BITMASK = 8L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static SMAAdmins toModel(SMAAdminsSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		SMAAdmins model = new SMAAdminsImpl();

		model.setId(soapModel.getId());
		model.setUserId(soapModel.getUserId());
		model.setRadcheckId(soapModel.getRadcheckId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setIsActive(soapModel.getIsActive());
		model.setCreatedOn(soapModel.getCreatedOn());
		model.setCreatedBy(soapModel.getCreatedBy());
		model.setUpdatedOn(soapModel.getUpdatedOn());
		model.setUpdatedBy(soapModel.getUpdatedBy());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<SMAAdmins> toModels(SMAAdminsSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<SMAAdmins> models = new ArrayList<SMAAdmins>(soapModels.length);

		for (SMAAdminsSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.pacnet.connect.model.SMAAdmins"));

	public SMAAdminsModelImpl() {
	}

	public long getPrimaryKey() {
		return _id;
	}

	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_id);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return SMAAdmins.class;
	}

	public String getModelClassName() {
		return SMAAdmins.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("id", getId());
		attributes.put("userId", getUserId());
		attributes.put("radcheckId", getRadcheckId());
		attributes.put("companyId", getCompanyId());
		attributes.put("isActive", getIsActive());
		attributes.put("createdOn", getCreatedOn());
		attributes.put("createdBy", getCreatedBy());
		attributes.put("updatedOn", getUpdatedOn());
		attributes.put("updatedBy", getUpdatedBy());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long id = (Long)attributes.get("id");

		if (id != null) {
			setId(id);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		Long radcheckId = (Long)attributes.get("radcheckId");

		if (radcheckId != null) {
			setRadcheckId(radcheckId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Integer isActive = (Integer)attributes.get("isActive");

		if (isActive != null) {
			setIsActive(isActive);
		}

		Date createdOn = (Date)attributes.get("createdOn");

		if (createdOn != null) {
			setCreatedOn(createdOn);
		}

		String createdBy = (String)attributes.get("createdBy");

		if (createdBy != null) {
			setCreatedBy(createdBy);
		}

		Date updatedOn = (Date)attributes.get("updatedOn");

		if (updatedOn != null) {
			setUpdatedOn(updatedOn);
		}

		String updatedBy = (String)attributes.get("updatedBy");

		if (updatedBy != null) {
			setUpdatedBy(updatedBy);
		}
	}

	@JSON
	public long getId() {
		return _id;
	}

	public void setId(long id) {
		_id = id;
	}

	@JSON
	public long getUserId() {
		return _userId;
	}

	public void setUserId(long userId) {
		_columnBitmask |= USERID_COLUMN_BITMASK;

		if (!_setOriginalUserId) {
			_setOriginalUserId = true;

			_originalUserId = _userId;
		}

		_userId = userId;
	}

	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	public long getOriginalUserId() {
		return _originalUserId;
	}

	@JSON
	public long getRadcheckId() {
		return _radcheckId;
	}

	public void setRadcheckId(long radcheckId) {
		_columnBitmask |= RADCHECKID_COLUMN_BITMASK;

		if (!_setOriginalRadcheckId) {
			_setOriginalRadcheckId = true;

			_originalRadcheckId = _radcheckId;
		}

		_radcheckId = radcheckId;
	}

	public long getOriginalRadcheckId() {
		return _originalRadcheckId;
	}

	@JSON
	public long getCompanyId() {
		return _companyId;
	}

	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	public int getIsActive() {
		return _isActive;
	}

	public void setIsActive(int isActive) {
		_columnBitmask |= ISACTIVE_COLUMN_BITMASK;

		if (!_setOriginalIsActive) {
			_setOriginalIsActive = true;

			_originalIsActive = _isActive;
		}

		_isActive = isActive;
	}

	public int getOriginalIsActive() {
		return _originalIsActive;
	}

	@JSON
	public Date getCreatedOn() {
		return _createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		_createdOn = createdOn;
	}

	@JSON
	public String getCreatedBy() {
		if (_createdBy == null) {
			return StringPool.BLANK;
		}
		else {
			return _createdBy;
		}
	}

	public void setCreatedBy(String createdBy) {
		_createdBy = createdBy;
	}

	@JSON
	public Date getUpdatedOn() {
		return _updatedOn;
	}

	public void setUpdatedOn(Date updatedOn) {
		_updatedOn = updatedOn;
	}

	@JSON
	public String getUpdatedBy() {
		if (_updatedBy == null) {
			return StringPool.BLANK;
		}
		else {
			return _updatedBy;
		}
	}

	public void setUpdatedBy(String updatedBy) {
		_updatedBy = updatedBy;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			SMAAdmins.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public SMAAdmins toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (SMAAdmins)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public Object clone() {
		SMAAdminsImpl smaAdminsImpl = new SMAAdminsImpl();

		smaAdminsImpl.setId(getId());
		smaAdminsImpl.setUserId(getUserId());
		smaAdminsImpl.setRadcheckId(getRadcheckId());
		smaAdminsImpl.setCompanyId(getCompanyId());
		smaAdminsImpl.setIsActive(getIsActive());
		smaAdminsImpl.setCreatedOn(getCreatedOn());
		smaAdminsImpl.setCreatedBy(getCreatedBy());
		smaAdminsImpl.setUpdatedOn(getUpdatedOn());
		smaAdminsImpl.setUpdatedBy(getUpdatedBy());

		smaAdminsImpl.resetOriginalValues();

		return smaAdminsImpl;
	}

	public int compareTo(SMAAdmins smaAdmins) {
		long primaryKey = smaAdmins.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		SMAAdmins smaAdmins = null;

		try {
			smaAdmins = (SMAAdmins)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long primaryKey = smaAdmins.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		SMAAdminsModelImpl smaAdminsModelImpl = this;

		smaAdminsModelImpl._originalUserId = smaAdminsModelImpl._userId;

		smaAdminsModelImpl._setOriginalUserId = false;

		smaAdminsModelImpl._originalRadcheckId = smaAdminsModelImpl._radcheckId;

		smaAdminsModelImpl._setOriginalRadcheckId = false;

		smaAdminsModelImpl._originalCompanyId = smaAdminsModelImpl._companyId;

		smaAdminsModelImpl._setOriginalCompanyId = false;

		smaAdminsModelImpl._originalIsActive = smaAdminsModelImpl._isActive;

		smaAdminsModelImpl._setOriginalIsActive = false;

		smaAdminsModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<SMAAdmins> toCacheModel() {
		SMAAdminsCacheModel smaAdminsCacheModel = new SMAAdminsCacheModel();

		smaAdminsCacheModel.id = getId();

		smaAdminsCacheModel.userId = getUserId();

		smaAdminsCacheModel.radcheckId = getRadcheckId();

		smaAdminsCacheModel.companyId = getCompanyId();

		smaAdminsCacheModel.isActive = getIsActive();

		Date createdOn = getCreatedOn();

		if (createdOn != null) {
			smaAdminsCacheModel.createdOn = createdOn.getTime();
		}
		else {
			smaAdminsCacheModel.createdOn = Long.MIN_VALUE;
		}

		smaAdminsCacheModel.createdBy = getCreatedBy();

		String createdBy = smaAdminsCacheModel.createdBy;

		if ((createdBy != null) && (createdBy.length() == 0)) {
			smaAdminsCacheModel.createdBy = null;
		}

		Date updatedOn = getUpdatedOn();

		if (updatedOn != null) {
			smaAdminsCacheModel.updatedOn = updatedOn.getTime();
		}
		else {
			smaAdminsCacheModel.updatedOn = Long.MIN_VALUE;
		}

		smaAdminsCacheModel.updatedBy = getUpdatedBy();

		String updatedBy = smaAdminsCacheModel.updatedBy;

		if ((updatedBy != null) && (updatedBy.length() == 0)) {
			smaAdminsCacheModel.updatedBy = null;
		}

		return smaAdminsCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(19);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", radcheckId=");
		sb.append(getRadcheckId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", isActive=");
		sb.append(getIsActive());
		sb.append(", createdOn=");
		sb.append(getCreatedOn());
		sb.append(", createdBy=");
		sb.append(getCreatedBy());
		sb.append(", updatedOn=");
		sb.append(getUpdatedOn());
		sb.append(", updatedBy=");
		sb.append(getUpdatedBy());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(31);

		sb.append("<model><model-name>");
		sb.append("com.pacnet.connect.model.SMAAdmins");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>radcheckId</column-name><column-value><![CDATA[");
		sb.append(getRadcheckId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>isActive</column-name><column-value><![CDATA[");
		sb.append(getIsActive());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createdOn</column-name><column-value><![CDATA[");
		sb.append(getCreatedOn());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createdBy</column-name><column-value><![CDATA[");
		sb.append(getCreatedBy());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>updatedOn</column-name><column-value><![CDATA[");
		sb.append(getUpdatedOn());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>updatedBy</column-name><column-value><![CDATA[");
		sb.append(getUpdatedBy());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = SMAAdmins.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			SMAAdmins.class
		};
	private long _id;
	private long _userId;
	private String _userUuid;
	private long _originalUserId;
	private boolean _setOriginalUserId;
	private long _radcheckId;
	private long _originalRadcheckId;
	private boolean _setOriginalRadcheckId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private int _isActive;
	private int _originalIsActive;
	private boolean _setOriginalIsActive;
	private Date _createdOn;
	private String _createdBy;
	private Date _updatedOn;
	private String _updatedBy;
	private long _columnBitmask;
	private SMAAdmins _escapedModelProxy;
}